### ISSUE TITLE
Make OnTextChangeEvent implement CharSequence

### ISSUE THREAD

**Issue by dalewking** [ReactiveX/RxAndroid#108]
In the old days when you subscribed to text changes for a view it was an Observable on just the text. Now it is an OnTextChangeEvent which includes the view and the text. It would be handy if OnTextChangeEvent actually implemented CharSequence delegating to the CharSequence member. The motivation is that it allows you to use functions that operate on CharSequence with the observable.

For example if you are only interested in events where the text is not empty you could use a filter function. If you have an existing function that determines if a CharSequence is not empty it cannot be used as you have to use a function on OnTextChangeEvent. Having it implement CharSequence allows you to use existing functions that operate on CharSequence.

**Comment by hamidp** [comment]
Can we resolve this as a won't fix?
