### ISSUE TITLE
Upgrading guide

### ISSUE THREAD

**Issue by ronshapiro** [ReactiveX/RxAndroid#109]
I think we can appease a lot of people's frustrations with changing APIs by being diligent about having an upgrade guide. It should be relatively easy to keep up to date; every time you break an API, just update a doc and when we release we consolidate all of those items.

**Comment by JakeWharton** [comment]
This is exactly what a `CHANGELOG.md` is for, which we can add. A separate doc and consolidation step is not needed.

**Comment by ronshapiro** [comment]
:+1:

**Comment by austynmahoney** [comment]
I agree that this is worthwhile. I just upgraded to `0.24` and I haven't found anything telling me that `AndroidObservable` is gone besides a vague commit message on the release commit log.

**Comment by JakeWharton** [comment]
Change log will be updated with breaking changes in the future. I've already gone ahead and documented `master`'s current changes.
