### ISSUE TITLE
Release 0.24.0

### ISSUE THREAD

**Issue by hamidp** [ReactiveX/RxAndroid#117]
Seems like a good time to do a release and get some more movement on the pending PRs.

Thoughts?

**Comment by iNoles** [comment]
AppObservable is much easier for any android developers without depend on lifecycle

**Comment by JakeWharton** [comment]
@mttkay got hit by a bus so we can't release. We have a very low bus factor on this project.

**Comment by mttkay** [comment]
I can't release either, since it goes through Netflix's build infra. You
will have to talk to Ben. He did all the releases for us so far.

**Comment by JakeWharton** [comment]
Will do. Thanks :+1:

**Comment by benjchristensen** [comment]
Doing so now.

**Comment by benjchristensen** [comment]
The Gradle/CloudBees config has something wrong so need to figure that out. /cc @quidryan Seems we need to upgrade to v2.x of the nebula plugin.

**Comment by benjchristensen** [comment]
@quidryan I tried upgrading to the new Nebula plugins and Gradle 2:

```
    classpath 'com.netflix.nebula:gradle-rxjava-project-plugin:2.+'
    classpath 'com.netflix.nebula:gradle-extra-configurations-plugin:2.+'
```

This then results in this failure:

```
* Where:
Build file '/Users/benjchristensen/development/github/ReactiveX/RxAndroid/sample-app/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating project ':sample-app'.
> Failed to apply plugin [id 'com.android.application']
   > Gradle version 1.10 is required. Current version is 2.2.1. If using the gradle wrapper, try editing the distributionUrl in /Users/benjchristensen/development/github/ReactiveX/RxAndroid/gradle/wrapper/gradle-wrapper.properties to gradle-1.10-all.zip
```

But I believe I need to be upgraded to `gradle-rxjava-project-plugin:2.+` in order for the new CloudBees config to work, and that requires Gradle 2.

**Comment by benjchristensen** [comment]
Is it expected to have a new artifact `rxandroid-framework` released to Maven Central?

**Comment by hamidp** [comment]
Yes.

**Comment by benjchristensen** [comment]
Thanks for the fast response @hamidp

**Comment by benjchristensen** [comment]
0.24.0 has been released. It is on its way to Maven Central and can be seen on BinTray at https://bintray.com/reactivex/RxJava/RxAndroid/view

I had to disable the `sample-app` module to get through the build process as I had to upgrade to Gradle 2. We can now deal with that issue separately.

**Comment by benjchristensen** [comment]
The goal is for releases to eliminate Jenkins/CloudBees and go through Travis so that anyone with commit privileges to RxAndroid can do a release just by committing a tag. The progress towards this is being tracked at https://github.com/ReactiveX/RxJava/issues/1810 since it will be done for all RxJava projects. 

/cc @jkschneider and @quidryan

**Comment by hamidp** [comment]
Thanks @benjchristensen !

**Comment by iNoles** [comment]
@benjchristensen in https://github.com/ReactiveX/RxAndroid/blob/0.x/sample-app/build.gradle, it is trying to load old gradle plugin 0.12.+, it should be 1.0.0

you may need http://tools.android.com/tech-docs/new-build-system/migrating-to-1-0-0 to change DSL for 1.0.0

**Comment by tomrozb** [comment]
It will be useful to point out in the README that `AndroidObservable` has been split into several classes. It took me some time to figure out that `bindActivity` is now part of the `AppObservable`

**Comment by JakeWharton** [comment]
That is not README-worthy content. See #109.

**Comment by benjchristensen** [comment]
Can someone update https://github.com/ReactiveX/RxAndroid/releases and https://github.com/ReactiveX/RxAndroid/blob/0.x/CHANGES.md for 0.24?
