### ISSUE TITLE
Cannot resolve method ' ViewObservable.text() '

### ISSUE THREAD

**Issue by zhongbaitu** [ReactiveX/RxAndroid#130]
I saw some post just like [Grokking RxJava, Part 4: Reactive Android](http://blog.danlew.net/2014/10/08/grokking-rxjava-part-4/). 

That post said : `ViewObservable.text() to observe whenever a TextView changes its content.`

But i cannot find `text()` in the class of  `ViewObservable`.  Just can use`clicks` and `bindView` .

Did the method `text()` had deprecated?

**Comment by kboyarshinov** [comment]
It is `WidgetObservable.text()` now.

**Comment by a497823463** [comment]
0.25.0

**Comment by SaitejaP** [comment]
Cannot resolve method "WidgetObservable.text()". I am using `rxjava:1.0.14` and` rxandroid:1.0.1`

**Comment by artem-zinnatullin** [comment]
@SaitejaP https://github.com/ReactiveX/RxAndroid/wiki#moved

**Comment by SaitejaP** [comment]
Got it. Thank you
