### ISSUE TITLE
Update to RxJava 1.0.6 ?

### ISSUE THREAD

**Issue by gre** [ReactiveX/RxAndroid#132]
Hi,

is it possible to have a new version of RxAndroid using the latest version of RxJava?

Thanks

**Comment by plastiv** [comment]
You can do it yourself by adding `compile "io.reactivex:rxjava:1.0.6"` into your `build.gradle` file. By default gradle will use the latest version if it finds duplicated dependencies which is the case you want.

**Comment by JakeWharton** [comment]
Feel free to send a PR but there will not be a release for this. Specify an explicit dependency if you want the newer version.

**Comment by gre** [comment]
Ok I understand. Thanks for the tips @plastiv

**Comment by JakeWharton** [comment]
Actually, we (incorrectly/stupidly/dangerously/carelessly) use a wildcard so the latest is pulled at the time of release. The next release will simply point to the latest at that moment and time.
