### ISSUE TITLE
"Error exists in the bytecode."

### ISSUE THREAD

**Issue by hotchemi** [ReactiveX/RxAndroid#133]
### Summary

When I try to open RxAndroid project, IDE says "Error exists in the bytecode.".

### Process

IntelliJ(or Android Studio)→File→Open→Choose root build.gradle→Use default gradle wrapper

And I met the following error message.

![image](http://i.gyazo.com/2dbba49f9a85a630e03c8270c3032c8b.png)

**Comment by taothreeyears** [comment]
you may need update your jdk

**Comment by hotchemi** [comment]
My current jdk version is 1.8.0_40. But it doesn't fix...
My os information is OSX 10.9.5.

**Comment by iNoles** [comment]
I think this is under java.lang.VerifyError.

**Comment by JakeWharton** [comment]
This is an issue with the Nebula plugin (likely since fixed or transient) which is not strictly RxAndroid-related.
