### ISSUE TITLE
Add Scheduler plugin support

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxAndroid#134]
For the main RxJava project there exists [RxJavaSchedulersHook](https://github.com/ReactiveX/RxJava/wiki/Plugins#rxjavaschedulershook), which is great for testing (since you can just set all Schedulers to `immediate()`, even if they would normally be on another thread).

I'd like to propose adding plugin support to RxAndroid as well, starting with support for hooking into `AndroidSchedulers`. There's basically no other way to test it properly, since a lot of the code provided uses `AndroidSchedulers.mainThread()` internally (e.g. `AndroidSubscriptions`). Thoughts?

**Comment by zsiegel** [comment]
I second this. We typically create wrapper object to make testing easier but a more native solution would be great.

**Comment by powerje** [comment]
Ha, I think something like this is basically what I was looking for in my StackOverflow question here: http://stackoverflow.com/questions/28521280/unit-testing-android-app-that-relies-on-robolectric-rxjava-rxandroid

Right now I'm using https://code.google.com/p/awaitility/ but being able to just force immediate schedulers everywhere sounds like it would be a big help.
