### ISSUE TITLE
Support for RxActionBarActivity?

### ISSUE THREAD

**Issue by nectarine** [ReactiveX/RxAndroid#144]
Do you have any plan to support ActionBarActivity inside of rxandroid-framework?
RxAndroid supports support-v4, but not appcompat-v7 ;)

**Comment by JakeWharton** [comment]
Base classes are not a scalable solution for a library. We will be favoring
composition everywhere.

**Comment by nectarine** [comment]
Right. Extending base class is bad idea for library architecture. (although it sometimes could be a very convenient solution ;))
It was a question about existing components and missing ones.

I believe that rxandroid-framework was built to solve a classic android problem.
**Background task and Android lifecycle easily conflicts.**

How can we solve this mismatch with pure RxAndroid?
Is there any suggested  way?

**Comment by hamidp** [comment]
@nectarine Take a look at LifecycleObservable.

**Comment by dimsuz** [comment]
It's just that currentl classes in `rx-android-framework` seem to encourage to go with inheritance.
If composition is to be favored, then what are the goals of `rx-android-framework`? Or will it be reworked?

**Comment by JakeWharton** [comment]
The other base classes have been removed from future releases. This also requires a dependency on appcompat which we cannot do. The "framework" module was also removed for future relases.
