### ISSUE TITLE
Support for GoogleApiClient things?

### ISSUE THREAD

**Issue by brennantaylor** [ReactiveX/RxAndroid#151]
What do people think of wrapping up some of the api's in google play services to play nicely with observables such as something that delivers `FusedLocationProvider` results and handles the client connection for you.

Would likely have to be a separate artifact so people not using google play services do not have to pull it in.

**Comment by dbachelder** [comment]
We are currently using:

https://github.com/mcharmas/Android-ReactiveLocation

More stuff like that would be great.

**Comment by JakeWharton** [comment]
Definitely not in the core, but might be useful. We want to make sure we are writing something that applies to everyone, not just a limited subset.

I'm working on a doc that will hopefully outline a strong, opinionated future for this library. Sharing soon.

**Comment by brennantaylor** [comment]
:+1:

**Comment by JakeWharton** [comment]
Please attempt this as a separate small library. As part of #172 we're not accepting new things into the core at this time.
