### ISSUE TITLE
[Discussion] Observables for Widgets and compat lib items

### ISSUE THREAD

**Issue by josmo** [ReactiveX/RxAndroid#153]
I'm finding that I'm starting to write lib code for different widgets.  I haven't seen anything to the strategy and focus for what this lib is going to be long term for Widgets and compat lib widgets.  One of the items I recently created was essentially OnSubscribeRecyclerViewScroll for the RecycleView which is in the appcomat-v7-RecyclerView android lib.

Any thoughts from maintainer folks on if we should continue to contribute Widgets and create a new project for compat libs or if we want all of them in this project or all of them out?

**Comment by JakeWharton** [comment]
I am working on a direction document.

**Comment by JakeWharton** [comment]
I'll be adding this to https://github.com/JakeWharton/RxBinding but per #172 this won't be going into RxAndroid core.
