### ISSUE TITLE
Too many launcher activities

### ISSUE THREAD

**Issue by IgorGanapolsky** [ReactiveX/RxAndroid#157]
Hello,
in your sample-app's AndroidManifest, you have:
`<category android:name="android.intent.category.LAUNCHER"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <action android:name="android.intent.action.MAIN"/>`
for all of your activities.  Why is that?

**Comment by JakeWharton** [comment]
There's no chooser activity so the only way to open any of them is individually (i.e., from the launcher). Having them all default is copy/pasta I'm sure. Feel free to send a PR. The sample app will be fixed long-term as part of the coming major changes to this library.
