### ISSUE TITLE
RxAppCompatActivity => ActionBarActivity is beeing deprecated

### ISSUE THREAD

**Issue by SalomonBrys** [ReactiveX/RxAndroid#160]
Since ActionBarActivity is beeing deprecated, rxandroid-framework should:

- Provide an RxAppCompatActivity class
- Deprecate RxActionBarActivity

**Comment by plastiv** [comment]
It looks like RxActionBarActivity was not implemented: https://github.com/ReactiveX/RxAndroid/issues/144

**Comment by JakeWharton** [comment]
We don't have anything with AppCompat so there's no specific action to take here.

**Comment by dimsuz** [comment]
Maybe #144 should be also closed in this case?
