### ISSUE TITLE
ViewObservable.clicks() creates silent exceptions

### ISSUE THREAD

**Issue by pakoito** [ReactiveX/RxAndroid#161]
The behaviour is correct, but creating and using a ViewObservable raises exceptions that are sent to an unaccesible database.

    Button thing;
    public Observable<OnClickEvent> thingClicks() {
        return ViewObservable.clicks(thing);
    }

Subscription

    onPauseUnsubscriptions.add(ui.thingClicks().subscribe());

Every time a new event is raised, a silent exception comes with it:

    04-23 18:06:00.927    820-23422/? E/DatabaseUtils﹕ Writing exception to parcel
    java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
            at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14643)
            at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2469)
            at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:688)
            at android.content.ContentProvider$Transport.call(ContentProvider.java:325)
            at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:275)
            at android.os.Binder.execTransact(Binder.java:404)
            at dalvik.system.NativeStart.run(Native Method)

Phone: Samsung Galaxy S4
OS level: 4.4.2
RxAndroid: 0.24.+
RxAndroid-framework: 0.24.+

**Comment by JakeWharton** [comment]
The stacktrace contains nothing of RxJava nor RxAndroid. What makes you think this library is at fault?

**Comment by pakoito** [comment]
The code is self contained, I've tried replacing it with hand-made subjects and the exception is not thrown. The exception comes every time the element is clicked, not after, not before, not on a timer, and happens whether the subscription runs code or not. I know the stacktrace is very barebones, but there is nothing else happening to justify it.

**Comment by JakeWharton** [comment]
The entirety of the code with which your snippet interacts is contained here: https://github.com/ReactiveX/RxAndroid/blob/0.x/rxandroid/src/main/java/rx/android/view/OnSubscribeViewClick.java, and none of it would have anything to do with the exception. Did you check that the PID of the log matches that of your app's process?

**Comment by pakoito** [comment]
I've looked into it and it's a problem with the ActivityManager that's leaked through the application.

Samsung.
