### ISSUE TITLE
Cancel a task

### ISSUE THREAD

**Issue by rpano** [ReactiveX/RxAndroid#164]
Hi, 

Can we cancel an Observable from the Subscriber ?

Thanks, Rafi.

**Comment by artem-zinnatullin** [comment]
Your question is not about RxAndroid, it's about RxJava in general. StackOverflow is better place for such questions.

A: `Subscriber` can unsubscribe itself from `Observable` and `Observable` may check that `Subscriber` is no longer subscribed and stop its work.

```java
Subscription subscription = Observable.create(new OnSubscribe<ResultType>{
  @Override public void onSubscribe(Subscriber<ResultType> subscriber) {
    if (subscriber.isUnsubscribed()) { // this is how Observable can understand that subscriber is no longer subscribed
      
    }
  }
}).subscribe(someSubscriber);

subscription.unsubscribe();
// someSubscriber won't receive new notifications from Observable
// Observable can stop its work
```

Also, `Subscriber` has `unsubscribe()` method, so you can do same thing without reference to `Subscription`

**Comment by rpano** [comment]
Ok sorry for posting it here.

However your solution is not working : there is not any onSubscribe(Subscriber<ResultType> subscriber) method to override into a Observable.OnSubscribe object.

**Comment by artem-zinnatullin** [comment]
Sorry,  my mistake , I meant  `call(Subscriber s)` in `Observable.OnSubscribe`.
