### ISSUE TITLE
sample compile error

### ISSUE THREAD

**Issue by luyang177** [ReactiveX/RxAndroid#167]
When I import this project, Ecllipse say"Project has no project.properties file! Edit the project properties to set one"

**Comment by JakeWharton** [comment]
This project builds with Gradle but it's half of an Android Gradle project. If Eclipse's Gradle support does not allow you to import the project then you'll have to use IntelliJ IDEA. In the future, and with any luck, it's likely that only the latest versions of Android Studio will be able to open the project.
