### ISSUE TITLE
[Discussion] Default behavior for LifecycleObservable

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxAndroid#169]
Spawned from discussion within #168

It turns out that `LifecycleObservable` is implemented in a brittle way - it won't work with some operators (if the operators are applied afterwards). We have a few options:

1. Warn people to use `LifecycleObservable` last, so that it only touches the final `Subscriber`. (This is currently how things stand).
1. Instead of unsubscribing, we call `onComplete` instead. This will work, but means that leaving an `Activity` or `Fragment` will result in `onComplete` being called, and some people might have been depending on `onComplete` for different reasons.
1. Instead of unsubscribing, we call `onError` instead with a special `Exception` that indicates the early termination was due to the lifecycle. This means everyone has to handle `onError` and ignore a lot of responses (which is a lot of work), but is technically another valid solution.

We also have secret option 4, which is to ditch `LifecycleObservable` entirely and try something else.

We'd like to settle on a reasonable default behavior rather than give options, especially since you `LifecycleObservable` is optional (you could manage your `Subscriptions` manually if you need to).

**Comment by erickok** [comment]
My vote is for 1. onComplete has, for me, a true meaning on the data stream and should not be called for meta purposes. For example, it is also not called when unsubscribing to note that no items will be emitted henceforth. The same argument holds for calling onError.

**Comment by akarnokd** [comment]
I think the trouble is when one leaves the Observable world throught subscribe() and toBlocking(). Therefore, instead of LifecycleObservable returning an Observable, it could return an class that exposes only the methods leaving the Observable world, but not the composition methods.

**Comment by dlew** [comment]
If we went that route and expressly forbade composition, then we could also just revert to the original setup, which was to use `CompositeSubscription` instead of a special takeUntil-esque operator.

**Comment by schwiz** [comment]
So for option 1. Using the bindUntilLifecycleEvent would always work correctly so long as don't call any other operators after?

**Comment by JakeWharton** [comment]
LifecycleObservable has been removed for future releases as part of #172. While it might come back in some form, you're much better off either emitting specific events for the lifecycle or explicitly unsubscribing in the callback.

**Comment by schwiz** [comment]
Hope to see it back I found this utility to be extremely helpful

**Comment by dimsuz** [comment]
By 'explicitly unsubscribing' you mean passing a `Subscriber` interface which has `unsubsribe()` method, instead of separate `onNext`, `onError`, `onComplete` actions to `subscribe()`?

**Comment by JakeWharton** [comment]
I mean put the returned `Subscriber` from your stream in a field (or a `CompositeSubscription` field) and call `unsubscribe` on it in whatever lifecycle callback you want.
