### ISSUE TITLE
Is the project actively maintained?

### ISSUE THREAD

**Issue by Konrad-Morawski** [ReactiveX/RxAndroid#171]
In particular I mean catching up to latest RxJava version. 

It's based on RxJava 1.0.4, which is half a year old - the latest version is RxJava 1.0.11.

**Comment by JakeWharton** [comment]
RxJava releases are source and binary compatible so there's no need to track its version. If you want the latest RxJava then you can depend on it directly.

**Comment by Konrad-Morawski** [comment]
Okay - so basically I can add a depedency on latest RxJava side-by-side with RxAndroid? 
Like so?

      compile 'io.reactivex:rxandroid:0.24.0'
      compile 'io.reactivex:rxjava:1.0.11'

Is it not going to lead to duplicating anything?

**Comment by artem-zinnatullin** [comment]
Yes. Gradle/Maven will choose latest version of dependency.
7 июня 2015 г. 5:37 PM пользователь "Konrad Morawski" <
notifications@github.com> написал:

**Comment by Konrad-Morawski** [comment]
That's perfect! Thanks for clearing that up.
