### ISSUE TITLE
[Proposal] RxSharedPreferences

### ISSUE THREAD

**Issue by henrytao-me** [ReactiveX/RxAndroid#178]
Hi there, 

This is my proposal about `RxSharedPreferences`. Please take a look. https://gist.github.com/henrytao-me/443e3c705ae375e22229 

I am very appreciate to have your comments / suggestions. I would like to create a PR too but I still don't know what package should I put it in. 

Cheer,
Henry

**Comment by iNoles** [comment]
I think this one should not to be a part of core library.

**Comment by JakeWharton** [comment]
As part of #172 we're not accepting new things into the core at this time.

**Comment by f2prateek** [comment]
There is an alternate library available for this as well https://github.com/f2prateek/rx-preferences :)
