### ISSUE TITLE
ReactiveDialog dismissed never terminate

### ISSUE THREAD

**Issue by gmarizy** [ReactiveX/RxAndroid#183]
ReactiveDialog may be dismissed without being cancelled, leaving a never ending Observable that leak. 

Is this a developer concern or should ReactiveDialog handle it like cancellation ?

**Comment by JakeWharton** [comment]
As part of #172, ReactiveDialog has been removed for future releases. The use cases and feature requests for this component are far too vast to be wrapped up in a single, core offering.
