### ISSUE TITLE
Release 0.25.0

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxAndroid#184]
`CHANGES.md` and `README.md` updated. Commit 4bff437edfa24dde62c90d44b019b9a35855db6a tagged as 'v0.25.0'.

@benjchristensen

**Comment by Saketme** [comment]
0.25 isn't available on MavenCentral yet. This could be confusing to new users who are trying to add RxAndroid in their project.

**Comment by JakeWharton** [comment]
That's why this issue exists.

**Comment by vashisthg** [comment]
+1, Either update README.md to fetch repo with v0.24.0 or update the version to mavencentral.

**Comment by benjchristensen** [comment]
Apparently the Travis based release process was never setup on this project, so it doesn't happen automatically. Working on that now.

**Comment by benjchristensen** [comment]
It is released to Bintray and Maven Central. It will take a few hours for Maven Central to show it in its search results, but it is available immediately on JCenter.

I updated the build files to support releasing via Travis.

**Comment by JakeWharton** [comment]
Thanks Ben!

**Comment by vashisthg** [comment]
Thanks
