### ISSUE TITLE
AppObservable bindFragment

### ISSUE THREAD

**Issue by aurozhkov** [ReactiveX/RxAndroid#187]
I execute all my network requests via Retrofit. To be sure that I don't update fragments at the wrong state, I wrapped all requests with `AppObservable.bindFragment()`, i.e.:
```
AppObservable.bindFragment(this, apiService.fetchSomething())
  .subscribe(new Action1<Object>() {
          @Override
          public void call(String fileName) {
             doSomething();
          }
       }, new Action1<Throwable>() {
           @Override
           public void call(Throwable throwable) {
             doSomething();
           }
       });
```
In `doSomething()` I update UI.
I caught a bug, when I was switching between screens very fast. I figured out that AppObservable uses the `fragment.isAdded() && !fragment.getActivity().isFinishing();` condition to check fragment's state. But as I understand it's possible, when fragment is added and doesn't have UI in the same time. I rewrote this conditional to `fragment.isVisible() && !fragment.getActivity().isFinishing();` and then crashes finished. 
What is the motivation to use such decision? Which cases is it suitable in?

**Comment by JakeWharton** [comment]
As part of #172, this API has been removed for future versions. Not only does the unsubscribe mechanisms go against an RxJava principle but it has potentially surprising effects. The story around fragments, as you noticed, is especially hairy. Your best solution would be to either explicitly unsubscribe in whatever lifecycle event you want or to use a retained fragment to keep the instance around across config changes.
