### ISSUE TITLE
Problem with running on background thread

### ISSUE THREAD

**Issue by dsvensson** [ReactiveX/RxAndroid#197]
I've probably misunderstood how to use the APIs (being new to Android, Groovy and Rx*), but I can't seem to get it working in any other way. I want to trigger a download of an image when clicking a button as a toy example to explore how RxAndroid works:

This works:

    ViewObservable.clicks(button, false)
                   .subscribe({ event -> text.text = "clicked"})

This, loosly based on the sample-app does not work:

    ViewObservable.clicks(button, false)
                    .subscribeOn(handlerThread(backgroundHandler))
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe({ event -> text.text = "clicked" })

But fails with the following error:

      07-09 02:14:55.015    1532-1549/android.process.acore E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at android.os.ParcelFileDescriptor.<init>(ParcelFileDescriptor.java:180)
            at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:916)
            at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:906)
            at android.app.IBackupAgent$Stub.onTransact(IBackupAgent.java:57)
            at android.os.Binder.execTransact(Binder.java:446)

I've also tried using Scheduler.newThread() in subscribeOn, with the same error.

What I try to do is the following:

    ViewObservable.clicks(button, false)
                    .map({ OnClickEvent event ->
                        def connection = (HttpURLConnection) new URL(url).openConnection()
                        try {
                            connection.connect()
                            connection.getInputStream().withStream {
                                BitmapFactory.decodeStream(it)
                            }
                        } finally {
                            connection.disconnect()
                        }
                    })
                    .subscribeOn(handlerThread(backgroundHandler))
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe({ Bitmap b -> imageView.imageBitmap = b })

This too fails with the same StrictMode complaint as the second example. All three calls are attempted in the onCreate method of my AppCompatActivity. 

Pushed the simple barebone repo here, main and only file can be found here:
https://github.com/nesouri/nesouri-app/blob/master/app/src/main/groovy/io/github/nesouri/MainActivity.groovy

This is all Android 22, tested with the emulator on Linux, and on Cyanogen 12.1 on a OnePlus One. A weird thing is that I don't enable StrictMode on my own, neither in code nor in emulator settings. Is it default nowdays? Anyways.. should ofc be StrictMode-clean.

I've also tried removing SwissKnife to see if that conflicted with RxAndroid in some bizarre way, but nopes.. same exception whenever using handlerThread(..) or Scheduler.newThread in onSubscribe.

**Comment by dsvensson** [comment]
Pushed the simple barebone repo here, main and only file can be found here:
https://github.com/nesouri/nesouri-app/blob/master/app/src/main/groovy/io/github/nesouri/MainActivity.groovy

**Comment by roman-mazur** [comment]
The log you provide here is not written by your app and does not seem to be related to your app (package name is `android.process.acore` that is an Android system core package).

**Comment by dsvensson** [comment]
Anywhere else to look? That is the only error message I can find in logcat when the app crashes. By removing the subscribeOn, the app stops crashing.

**Comment by JakeWharton** [comment]
```java
ViewObservable.clicks(button, false)
                .subscribeOn(handlerThread(backgroundHandler))
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe({ event -> text.text = "clicked" })
```
View-based observables *must* be subscribed to on the main thread. 
```java
ViewObservable.clicks(button, false)
                .observeOn(handlerThread(backgroundHandler))
                .map({ OnClickEvent event ->
                    def connection = (HttpURLConnection) new URL(url).openConnection()
                    try {
                        connection.connect()
                        connection.getInputStream().withStream {
                            BitmapFactory.decodeStream(it)
                        }
                    } finally {
                        connection.disconnect()
                    }
                })
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe({ Bitmap b -> imageView.imageBitmap = b })
```
This will implicitly subscribe synchronously up the chain since there is no `subscribeOn` and I'm assuming you are creating this on the main thread. If that's not the case, put `subscribeOn(mainThread())` as the very first operator.

**Comment by dsvensson** [comment]
Thank you very much for clearing that up. Works great now.
