### ISSUE TITLE
Feature Request: unit tests

### ISSUE THREAD

**Issue by IgorGanapolsky** [ReactiveX/RxAndroid#198]
Hi,
is there any way you can demo some unit tests of Observables?  I'd love to see how you pass mocks and use RX tests.

Thanks,
Igor

**Comment by artem-zinnatullin** [comment]
How is it related to RxAndroid?

**Comment by JakeWharton** [comment]
This is the subject for blog posts and comprehensive sample repositories, not a library. It's also about RxJava not RxAndroid which exists solely to provide some simple Android interfaces to RxJava paradigms.

**Comment by IgorGanapolsky** [comment]
@artem-zinnatullin There is a sample app in RxAndroid.  Don't you think sample apps could benefit from unit tests??

**Comment by JakeWharton** [comment]
The sample app consists of a single activity with extremely contrived contents. Activities should be integration/functional tested with instrumentation, not unit tests.

**Comment by artem-zinnatullin** [comment]
+1 to Jake, if you want to know about unit testing of Rx code, take a look at this article https://medium.com/ribot-labs/unit-testing-rxjava-6e9540d4a329

Also, check `TestSubscriber` and `TestObserver` classes from RxJava.

There is no much difference between regular unit testing and unit testing of Rx code, you just need some way to record emission of `Observable` (`TestSubscriber` & `TestObserver`) and execute it as blocking call (`toBlocking()`) or wait until it completes.
