### ISSUE TITLE
Sample code is outdated?

### ISSUE THREAD

**Issue by kamoljan** [ReactiveX/RxAndroid#201]
Hi guys

Where is `import rx.android.schedulers.HandlerScheduler;` in the [sample](https://github.com/ReactiveX/RxAndroid/blob/0.x/sample-app/src/main/java/rx/android/samples/MainActivity.java#L13) code?

Best regards
Kamol

**Comment by f2prateek** [comment]
Not sure what you mean, [this is the line](https://github.com/ReactiveX/RxAndroid/blob/0.x/sample-app/src/main/java/rx/android/samples/MainActivity.java#L43) where the sample references it and [this is the source](https://github.com/ReactiveX/RxAndroid/blob/0.x/rxandroid/src/main/java/rx/android/schedulers/HandlerScheduler.java) where it is defined.

**Comment by JakeWharton** [comment]
Also worth noting the sample reflects the code on master which is not the same as the code in the latest release. If you want to look at a sample for a released version, use the dropdown on GitHub or clone the project and check out the associated tag.
<img width="371" alt="screen shot 2015-07-21 at 1 32 59 am" src="https://cloud.githubusercontent.com/assets/66577/8793686/75dc6c06-2f48-11e5-8b39-6ca43fc37abd.png">

**Comment by kamoljan** [comment]
@JakeWharton I think you are right. It is exactly this issue.
