### ISSUE TITLE
Lifecycle support 

### ISSUE THREAD

**Issue by warabei14** [ReactiveX/RxAndroid#203]
Are there any plans to implement Android lifecycle support (recreating over rotation)?  I've seen some workarounds in the Internet, but afaiu it is some kind of the DIY LoaderManager approach. Maybe I would make a pull request, if I have enough time and it is interesting to somebody but me.

**Comment by JakeWharton** [comment]
No. There are WIP lifecycle APIs in place over at https://github.com/trello/RxLifecycle though.
