### ISSUE TITLE
throwing fatal exceptions 

### ISSUE THREAD

**Issue by mshearer123** [ReactiveX/RxAndroid#209]
Hi 

I'd like to use RxAndroid within our android app, but as a trail I am limiting it to some simple api calls.

I'm not sure I fully understand when the Rx sequence ends.  OK onError() feeds back any error's during the API sequence,  but what about after, when you want to process the response.   Should I expect to see all exceptions from that point on go through onError()?

Example of crashing on an npe.  Observable comes from Retrofit.
```
        AppObservable.bindFragment(this, getApiCallObservable())
                .subscribeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<ResponseModel>() {
                    @Override
                    public void onCompleted() {
                        uninitializedList.add("item");
                    }

                    @Override
                    public void onError(Throwable e) {
                        Log.e(TAG, "throwable: " + e.getMessage());
                    }

                    @Override
                    public void onNext(ResponseModel response) {
        
                    }
                });

**Comment by dlew** [comment]
This is a question about RxJava, not RxAndroid - RxJava provides the Observable pattern, RxAndroid just provides some utilities on top of that for Android.

In addition, please use the RxJava mailing list or StackOverflow for usage questions. This issue tracker is for bugs and feature requests only.

**Comment by gvan** [comment]
I have the same problem, exceptions not showing in logs. Can you provide related links how to solve this?
