### ISSUE TITLE
The right way to do UI stuff when transform Observable?

### ISSUE THREAD

**Issue by zhouhaibing089** [ReactiveX/RxAndroid#222]
I met a problem which can be described as following..
```
fetch topic detail => load all the replies on it => done
```
I want to do some ui stuff when I'm done fetching topic detail, of course the following demo code complains that ui stuff can only be done on main thread..
```java
mAPI.getTopic(id).flatMap(topic -> {
  // dismiss the loading animation and setup the adapter with no reply..
  spinner.stop();
  mAdapter = new ReplyListAdapter(/* args */);
  mListView.setAdapter(mAdapter);
  return mAPI.getReplyList(id);
}).observeOn(AndroidSchedulers.mainThread()).subscribe(/* handle the reply list */);
```
So here I wanna to know where should I put the `dismiss loading animation and...` code.. Thank you in advance..

**Comment by JakeWharton** [comment]
There's lots of ways to do this. Here's the quickest, which is not necessarily the most correct:
```java
api.getTopic(id)
    .observeOn(mainThread())
    .doOnNext(topic -> {
        spinner.stop();
        adapter = new ReplyListAdapter(/* args */);
        listView.setAdapter(adapter);
    })
    .flatMap(topic -> api.getReplyList(id))
    .observeOn(mainThread())
    .subscribe(/* whatever */);
```
In the future, you'll have better luck on the RxJava mailing list or on StackOverflow with the 'rx-android' tag. GitHub issues are for bugs and feature requests only.
