### ISSUE TITLE
Add copyright attribution?

### ISSUE THREAD

**Issue by larham** [ReactiveX/RxAndroid#225]
In order to satisfy a client lawyer who insists that an attribution is necessary even for apache licences, I need an official copyright attribution for RxAndroid.

Is there one?

One easy example from Guava is something like "copyright 2015 The authors of Guava". It has to be stated in a file on the github site or via email. We'll continue reaching out via email too.

Thanks,

Larry

**Comment by JakeWharton** [comment]
Since this project is neither sponsored by a company nor a participant in an open source foundation, I think we will take a similar approach to Guava. I'll will send a PR to update the relevant things shortly.
