### ISSUE TITLE
Should view binding observables operate on the main thread scheduler by default?

### ISSUE THREAD

**Issue by danhawkes** [ReactiveX/RxAndroid#231]
Current observable creation requires a lot of boilerplate:

    View.clicks(myView)
    .subscribeOn(AndroidSchedulers.mainThread())
    .unsubscribeOn(AndroidSchedulers.mainThread())

Given that subscribe/unsubscribe /must/ be called on the main thread, would it make sense for these methods to have a default scheduler?

**Comment by dlew** [comment]
You don't have to call either of those.

**Comment by JakeWharton** [comment]
RxJava streams emit values and subscribe synchronously by default. You actually can potentially cause subtle threading bugs by adding needless subscriptions like that. So like Dan said, if you're on the main thread, just omit both of those operator calls.
