### ISSUE TITLE
Proposal: Move RxBinding's MainThreadSubscription into RxAndroid

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxAndroid#232]
`MainThreadSubscription` is a handy way to create main thread `Observables` on Android. I've found a need for it in more than just RxBinding (especially if anyone ever wants to start creating an RxBinding-like solution for things beyond views and widgets).

What do others think?

**Comment by mttkay** [comment]
Could you link to it for reference? I'm unfamiliar with `MainThreadSubscription`

**Comment by dlew** [comment]
https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/internal/MainThreadSubscription.java

**Comment by dlew** [comment]
An example of it in action here: https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewClickOnSubscribe.java#L30-L34

**Comment by JakeWharton** [comment]
It's a more efficient version of what was `AndroidSubscriptions.unsubscribeInUiThread` in this library:
```java
    public static Subscription unsubscribeInUiThread(final Action0 unsubscribe) {
        return Subscriptions.create(new Action0() {
            @Override
            public void call() {
                if (Looper.getMainLooper() == Looper.myLooper()) {
                    unsubscribe.call();
                } else {
                    final Worker inner = AndroidSchedulers.mainThread().createWorker();
                    inner.schedule(new Action0() {
                        @Override
                        public void call() {
                            unsubscribe.call();
                            inner.unsubscribe();
                        }
                    });
                }
            }
        });
    }
```

**Comment by mttkay** [comment]
Thanks — I see, we need to run the unsubscribe closure on the main thread
whenever it needs to mutate a view.

That makes sense to me. I suppose it could live in the main library.

On Tue, Oct 6, 2015 at 5:23 PM, Daniel Lew <notifications@github.com> wrote:

> An example of it in action here:
> https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewClickOnSubscribe.java#L30-L34
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxAndroid/issues/232#issuecomment-145898695>
> .
>



-- 

Matthias Käppler

*Engineer*


Twitter: https://twitter.com/mttkay

Skype: matthias-sc



SoundCloud Ltd. | Rheinsberger Str. 76/77, 10115 Berlin, Germany | +49
(0)172 2345679

Managing Director: Alexander Ljung | Incorporated in England & Wales
with Company
No. 6343600 | Local Branch Office | AG Charlottenburg  | HRB 110657B



Capture and share your music & audio on SoundCloud
<http://soundcloud.com/creators>

**Comment by sddamico** [comment]
Any further thoughts on this? Would be a valuable addition to this library.

**Comment by JakeWharton** [comment]
I don't have a strong opinion. I'd certainly be happy to remove it from RxBinding.

As part of this, I think a main thread assertion static method is also in order on this type. This usually accompanies the use of this type as the precondition for the initial subscription.
