### ISSUE TITLE
Unit testing support for AndroidSchedulers

### ISSUE THREAD

**Issue by konmik** [ReactiveX/RxAndroid#238]
Currently when using `mainThread()` in a usual Unit Test, (even with an installed hook scheduler) I get
```
Caused by: java.lang.RuntimeException: Method getMainLooper in android.os.Looper not mocked. See http://g.co/androidstudio/not-mocked for details.
	at android.os.Looper.getMainLooper(Looper.java)
	at rx.android.schedulers.AndroidSchedulers.<clinit>(AndroidSchedulers.java:27) `
```
error.

So, it would be great to apply the original RxJava pattern without instantiating the defauilt scheduler during static initialization.

The curret workaround is `@SuppressStaticInitializationFor("rx.android.schedulers.AndroidSchedulers")` from PowerMock.

**Comment by felipecsl** [comment]
i currently use the code below for reference, but I guess you have a different problem here

```java
class TestRxAndroidSchedulersHook extends RxAndroidSchedulersHook {
    @Override
    public Scheduler getMainThreadScheduler() {
        return Schedulers.immediate();
    }
}
```

**Comment by JakeWharton** [comment]
The problem is that classloading will trigger the static init block of
AndroidSchedulers even if you override like that. If you are using the
Android unit test plugin without the default setting to true, this will
fail the build with the above error due to the getLooper() call.

**Comment by artem-zinnatullin** [comment]
To avoid that we use a level of indirection, so we can change schedulers in
the tests.

Also our Presenters does not know about the thread that view level operates
on since we think that it's a detail of View implementation.

Felipe: ^ what Jake wrote, probably you run everything under Robolectric
and just don't see the problem since Robolectric provides implementation of
Handler. We found that tests run slightly faster without Robolectric so if
we don't need to have things like Intents, etc — we run it under regular
JUnit runner.

Just sharing our experience, maybe someone would found it useful.

On Wed, Nov 11, 2015, 21:41 Jake Wharton <notifications@github.com> wrote:

> The problem is that classloading will trigger the static init block of
> AndroidSchedulers even if you override like that. If you are using the
> Android unit test plugin without the default setting to true, this will
> fail the build with the above error due to the getLooper() call.
>
> On Wed, Nov 11, 2015 at 1:40 PM Felipe Lima <notifications@github.com>
> wrote:
>
> > i currently use the code below for reference, but I guess you have a
> > different problem here
> >
> > class TestRxAndroidSchedulersHook extends RxAndroidSchedulersHook {
> > @Override
> > public Scheduler getMainThreadScheduler() {
> > return Schedulers.immediate();
> > }
> > }
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ReactiveX/RxAndroid/issues/238#issuecomment-155871758>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxAndroid/issues/238#issuecomment-155872431>
> .
>
-- 

@artem_zin

**Comment by felipecsl** [comment]
Yep, I use Robolectric and yeah, it takes forever.

**Comment by ivacf** [comment]
Is this fix going to be push to maven central soon?

**Comment by preslavrachev** [comment]
I hit a similar situation today, when I wanted to unit test one of my presenters outside of Android. I think that I'll follow @artem-zinnatullin's advice and take `subscribeOn` and `observeOn` out of the presenter. There is an `ApplicationContext` instance that gets passed as a dependency to all of my presenters, and supplies them with Retrofit-based APIs. I'll wrap each of the API services with Scheduler logic there, and get my presenters clean off any platform dependencies.

**Comment by Plastix** [comment]
I'm having a hard time understanding the discussion here. Where should I be setting my schedulers? 

I have an interactor that wraps a Retrofit service. Currently I am applying schedulers to the Observable returned by Retrofit using transformers in the interactor. This interactor is then used by my presenter. I'm testing my interactor with a regular JUnit runner and registering a `RxAndroidSchedulersHook` that returns `Schedulers.immediate()`. Is this the correct way of doing it?

**Comment by konmik** [comment]
It became almost impossible to use such way of injection with the latest rxjava release for me. RxJava creates even more internal instances of schedulers now randomly, so my tests became flaky.

So now I switched to Dagger injected schedulers, they work much better.

**Comment by ivacf** [comment]
We've been using this [Junit test rule](https://github.com/ribot/android-boilerplate/blob/master/app/src/test/java/uk/co/ribot/androidboilerplate/util/RxSchedulersOverrideRule.java) for a while and it seems to be working fine so far. It uses reflection to call the `reset()` method. 
You have to add it to every test class that tests app code containing RxJava dependencies so you make sure the schedulers are not initialised before the rule is executed. It's not ideal but it's the best solution I've found some far.

**Comment by Plastix** [comment]
Thank you @ivacf! This is exactly what I am looking for.

**Comment by initialjie** [comment]
Thank you @ivacf!  It works like a warm.

**Comment by marcoRS** [comment]
The Rule suggested @ivacf works well for me when I run one test class in isolation but when I run all my tests some fail with errors related to mock methods not being called. Anyone run into this? 

Is there any other alternatives to using the test Rule?

**Comment by adityaladwa** [comment]
Hello @marcoRS the rule by @ivacf works fine for me. 
Check out the Test

https://github.com/LadwaAditya/TwiTone-Android/blob/master/app/src/test/java/com/ladwa/aditya/twitone/login/LoginPresenterTest.java

**Comment by afjoseph** [comment]
Not sure if its related to this issue, but just wanted to say that RxJava2 changed a few things about how to override schedulers. I found another way outlined here: http://stackoverflow.com/a/43320828/3870025
