### ISSUE TITLE
A scheduler for currentThread ?

### ISSUE THREAD

**Issue by manidesto** [ReactiveX/RxAndroid#244]
I know we can kind of get it done by using 
`HandlerSchedulers.from(new Handler(Looper.myLooper()))` 
Is there any reasons this is not provided?

**Comment by JakeWharton** [comment]
It's not included because no one has asked for it and the use cases for it are not widely applicable to all apps. Please provide examples of when something like this is useful and where `Schedulers.trampoline()` and `Schedulers.immediate()` are not suitable.

**Comment by manidesto** [comment]
Makes sense.
