### ISSUE TITLE
How to get Header from RxAndroid Response?

### ISSUE THREAD

**Issue by MuraliGanesan** [ReactiveX/RxAndroid#245]
This is the function which i used for the network calls.

    private void generateNewCard()
    {
        showProgressDialog();
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(NetworkCalls.BASE_URL)
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .build();

        NetworkCalls.CustomerApi customerApi = retrofit.create(NetworkCalls.CustomerApi.class);

        customerApi.addExistingCard(prefs.getString(Constants.AUTH_TOKEN, ""), "", CREATE_NEW_CARD)
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<DataGeneral>() {

                    @Override
                    public void onCompleted() {
                        stopProgressDialog();
                        Log.d(TAG, "onCompleted DataGeneral" + DataGeneral.class);
                    }

                    @Override
                    public void onError(Throwable e) {
                        Log.d(TAG, "onError" + e.getMessage());
                        stopProgressDialog();
                    }

                    @Override
                    public void onNext(DataGeneral data) {

                        stopProgressDialog();
                        if (data.getStatus() == 1) {

                        }
                    }
                });
    }

and the interface class is here,

      @FormUrlEncoded
        @POST("add-loyalty-card")
        Observable<DataGeneral> addExistingCard(@Field("Token") String token, @Field("cardHas") String cardHas, @Field("ltyCardId") String ltyCardId);

This works fine for me. I am getting desired result. I wish to know how can i get the Header from the response and is there a way to simplify the above code?

Any help would be really appreciated.

**Comment by artem-zinnatullin** [comment]
Question is not related to RxAndroid at all, it's about RxJava + Retrofit
and StackOverflow is a better place for such questions.

On Fri, Dec 4, 2015 at 10:38 AM MuraliGanesan <notifications@github.com>
wrote:

> This is the function which i used for the network calls.
>
> private void generateNewCard()
> {
>     showProgressDialog();
>     Retrofit retrofit = new Retrofit.Builder()
>             .baseUrl(NetworkCalls.BASE_URL)
>             .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
>             .addConverterFactory(GsonConverterFactory.create())
>             .build();
>
>     NetworkCalls.CustomerApi customerApi = retrofit.create(NetworkCalls.CustomerApi.class);
>
>     customerApi.addExistingCard(prefs.getString(Constants.AUTH_TOKEN, ""), "", CREATE_NEW_CARD)
>             .subscribeOn(Schedulers.newThread())
>             .observeOn(AndroidSchedulers.mainThread())
>             .subscribe(new Observer<DataGeneral>() {
>
>                 @Override
>                 public void onCompleted() {
>                     stopProgressDialog();
>                     Log.d(TAG, "onCompleted DataGeneral" + DataGeneral.class);
>                 }
>
>                 @Override
>                 public void onError(Throwable e) {
>                     Log.d(TAG, "onError" + e.getMessage());
>                     stopProgressDialog();
>                 }
>
>                 @Override
>                 public void onNext(DataGeneral data) {
>
>                     stopProgressDialog();
>                     if (data.getStatus() == 1) {
>
>
>                     }
>                 }
>             });
> }
>
> and the interface class is here,
>
>   @FormUrlEncoded
>     @POST("add-loyalty-card")
>     Observable<DataGeneral> addExistingCard(@Field("Token") String token, @Field("cardHas") String cardHas, @Field("ltyCardId") String ltyCardId);
>
> This works fine for me. I am getting desired result. I wish to know how
> can i get the Header from the response and is there a way to simplify the
> above code?
>
> Any help would be really appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxAndroid/issues/245>.
>
-- 

@artem_zin

**Comment by JakeWharton** [comment]
It was posted to both simultaneously.

http://stackoverflow.com/questions/34082641/how-to-get-header-from-rxandroid-response
