### ISSUE TITLE
i have not find AppObservable

### ISSUE THREAD

**Issue by k-lam** [ReactiveX/RxAndroid#249]
i have not find AppObservable

**Comment by artem-zinnatullin** [comment]
It's not part of RxAndroid anymore, please check the wiki page of this
repository to see why and what are the alternatives. Would be nice if you
would close the issue :)

On Mon, Dec 7, 2015 at 11:06 AM k-lam <notifications@github.com> wrote:

> i have not find AppObservable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxAndroid/issues/249>.
>
-- 

@artem_zin
