### ISSUE TITLE
Using old version of RxJava?

### ISSUE THREAD

**Issue by psyren89** [ReactiveX/RxAndroid#250]
In my `build.gradle` file, I have:
```
compile 'io.reactivex:rxandroid:1.0.1'
compile 'io.reactivex:rxjava:1.1.0'
```

Running `./gradlew app:dependencies` gives me this:
```
...
+--- io.reactivex:rxandroid:1.0.1
|    \--- io.reactivex:rxjava:1.0.13 -> 1.1.0
...
```

Does this imply that RxAndroid is still leaning on version 1.0.13 of RxJava by default?

**Comment by vanniktech** [comment]
Yup RxAndroid still relies upon 1.0.13 of RxJava. If you however specify a new rxjava dependency that one will be overridden. As you can see here `1.0.13 -> 1.1.0`

From the README:

> // Because RxAndroid releases are few and far between, it is recommended you also
// explicitly depend on RxJava's latest version for bug fixes and new features.

**Comment by psyren89** [comment]
I understand that newer provided dependencies will override older ones, but my confusion arises from seeing commits like [this](https://github.com/ReactiveX/RxAndroid/commit/bb2e8bf70c98bfdc6dbe890d396e3f1ed0325eaa)...

**Comment by vanniktech** [comment]
Well we still do update the dependencies though all of those commits are not yet released so you won't see a change. The moment we bump the RxAndroid version we'll try to also have the latest RxJava version as a dependency.

**Comment by psyren89** [comment]
Aha, that makes sense. Cheers.
