### ISSUE TITLE
how to get error body in Rxandroid?

### ISSUE THREAD

**Issue by MuraliGanesan** [ReactiveX/RxAndroid#251]
This is the function which i used for the network calls.

     private void getSample() {
    Log.d("", "getSample : ");
    OkHttpClient client = new OkHttpClient();

    HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
    interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
    client.interceptors().add(interceptor);

    Retrofit retrofit = new Retrofit.Builder()
            .baseUrl(NetworkCalls.BASE_URL)
            .client(client)

            .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
            .addConverterFactory(GsonConverterFactory.create())
            .build();
    NetworkCalls.CustomerApi customerApi = retrofit.create(NetworkCalls.CustomerApi.class);

    Log.e("customerApi  Created", "customerApi object Created : ");

    customerApi.getCategories("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjgsImlzcyI6Imh0dHA6XC9cLzE5Mi4xNjguMS42MDo4ODg4XC9DQ1YzXC9wdWJsaWNcL2FwaVwvbG9naW4iLCJpYXQiOjE0NDk0ODg5NDMsImV4cCI6MTQ0OTQ5MjU0MywibmJmIjoxNDQ5NDg4OTQzLCJqdGkiOiI0ODY4ZmNmZDk4OTIxZGQwYjA2ZDZlN2EyYjRjZGMxMSJ9.7c60LRQMFCtqprCbbULgR5xG-FxwXnRUZPuWeMJXcNE")
            .subscribeOn(Schedulers.newThread())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(new Subscriber<Response<DataCategoryList>>() {
                @Override
                public void onCompleted() {

                    Log.e("onCompleted", "onCompleted : ");

                }

                @Override
                public void onError(Throwable e) {
                    Log.e("onError", "onError : " + e.getMessage());
                    e.printStackTrace();

                    // network errors, e. g. UnknownHostException, will end up here
                }

                @Override
                public void onNext(Response<DataCategoryList> startupResponseResponse) {

                }
            });
}

Interface class

    public interface CustomerApi {
    @Headers({
            "Accept: application/json"
    })
    @FormUrlEncoded
    @POST("categories")
    Observable<Response<DataCategoryList>> getCategories(@Field("token") String token);

    }

Every thing is working fine.  When i give input as invalid token. How to get error message in that response.

   12-09 16:03:11.148 27751-28255/com.cc.customer D/OkHttp: <-- HTTP/1.1 401 Unauthorized (642ms)
   12-09 16:03:11.148 27751-28255/com.cc.customer D/OkHttp: Date: Wed, 09 Dec 2015 10:33:15 GMT
    12-09 16:03:11.148 27751-28255/com.cc.customer D/OkHttp: Server: Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zg DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
    12-09 16:03:11.148 27751-28255/com.cc.customer D/OkHttp: X-Powered-By: PHP/5.6.10
    12-09 16:03:11.148 27751-28255/com.cc.customer D/OkHttp: Cache-Control: no-cache
    12-09 16:03:11.148 27751-28255/com.cc.customer D/OkHttp: Set-Cookie: XSRF-TOKEN=PRy2B7N6lrbqdnLUbtjuLhKDCQABpesE1C6lCE1u; expires=Wed, 09-Dec-2015 12:33:15 GMT; Max-Age=7200; path=/
    12-09 16:03:11.148 27751-28255/com.cc.customer D/OkHttp: Set-Cookie: laravel_session=e4130b5451f2a435b96d749329190ad7371ef8b6; expires=Wed, 09-Dec-2015       12:33:15 GMT; Max-Age=7200; path=/; httponly
    12-09 16:03:11.148 27751-28255/com.cc.customer D/OkHttp: Content-Length: 31
    12-09 16:03:11.148 27751-28255/com.cc.customer D/OkHttp: Keep-Alive: timeout=5, max=100
   12-09 16:03:11.148 27751-28255/com.cc.customer D/OkHttp: Connection: Keep-Alive
   12-09 16:03:11.149 27751-28255/com.cc.customer D/OkHttp: Content-Type: application/json
   12-09 16:03:11.149 27751-28255/com.cc.customer D/OkHttp: OkHttp-Selected-Protocol: http/1.1
   12-09 16:03:11.149 27751-28255/com.cc.customer D/OkHttp: OkHttp-Sent-Millis: 1449657190827
   12-09 16:03:11.149 27751-28255/com.cc.customer D/OkHttp: OkHttp-Received-Millis: 1449657191145
    12-09 16:03:11.152 27751-28255/com.cc.customer D/OkHttp: {"error":"invalid_credentials"}
    12-09 16:03:11.152 27751-28255/com.cc.customer D/OkHttp: <-- END HTTP (31-byte body)

 Any help would be really appreciated.

**Comment by plastiv** [comment]
Hello!
Take a look at the retrofit sample over here: https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/DeserializeErrorBody.java#L68

Btw, mainterners of the project are aim to reserve github issue usages to track bugs and feature requests only. Asking for developer help is adviced to do at https://stackoverflow.com/search?q=%5Bretrofit%5D+how+to+get+error+body
