### ISSUE TITLE
In what project can we find updated AndroidObservable.fromBroadcast()?

### ISSUE THREAD

**Issue by teddis** [ReactiveX/RxAndroid#259]

**Comment by vanniktech** [comment]
Are you looking for that [one](https://github.com/Laimiux/rxnetwork-android/blob/37e81934b5dd1296ef345e57f8ccafdec55bfabb/library/src/main/java/com/laimiux/rxnetwork/ContentObservable.java)? (I just searched for fromBroadcast in Github itself)

**Comment by teddis** [comment]
Thanks, found that too, but its private so can't be used! Maybe I should submit a PR? Or is there a better supported project with `fromBroadcast` functionality. It's great TPTB split into sub projects, but appears the process was not documented very well. Was `fromBroadcast`, for example, deprecated for a reason? If not, which project did it migrate to?

**Comment by MyDogTom** [comment]
It's documented in Wiki. Take a look [Wiki -> Orphaned](https://github.com/ReactiveX/RxAndroid/wiki#orphaned)
>The rest of ContentObservable has yet to make the move. This could be a good project for someone looking to do some open source work!

**Comment by teddis** [comment]
Thank you, @MyDogTom!

**Comment by JakeWharton** [comment]
There's also an RxBroadcast project on GitHub.

Closing since there's no action to take on this project.

**Comment by teddis** [comment]
Thanks @JakeWharton

**Comment by jeffery812** [comment]
is RxBroadcast an official one? it seems not so many people are using it. is it safe to me to use RxBroadcast?
