### ISSUE TITLE
java.lang.NoClassDefFoundError: rx.plugins.RxJavaPlugins

### ISSUE THREAD

**Issue by esmas-antoni** [ReactiveX/RxAndroid#261]
I am obtaining the exception: 
**java.lang.NoClassDefFoundError: rx.plugins.RxJavaPlugins**
when I install an application with RxAndroid framework in a device or emulator with API version 4.4.x (KitKat).

Is this a possible issue?

Thank you

**Comment by artem-zinnatullin** [comment]
Probably, you're not initializing MultiDex correctly, can you please check
it?

On Mon, Jan 11, 2016, 12:45 esmas-antoni <notifications@github.com> wrote:

> I am obtaining the exception:
> *javalangNoClassDefFoundError: rxpluginsRxJavaPlugins*
> when I install an application with RxAndroid framework in a device or
> emulator with API version 44x (KitKat)
>
> Is this a possible issue?
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxAndroid/issues/261>.
>
-- 

@artem_zin

**Comment by esmas-antoni** [comment]
Yes, I'm not initializing Multidex... I'm sorry. Thanks.

**Comment by artem-zinnatullin** [comment]
:+1:
