### ISSUE TITLE
Write some examples to RxAndroid

### ISSUE THREAD

**Issue by YongHuiLuo** [ReactiveX/RxAndroid#262]
@All  Because interest RxAndroid project, write some examples RxAndroid used in the learning process,In addition, the use of Chinese compile a RxAndroid PPT related documentation.
The address of the project is https://github.com/YongHuiLuo/Learning-Rxandroid.
I sincerely hope that my example of contributors point out shortcomings, but also hope that through our efforts to help more people understand RxAndroid and use her.

**Comment by beautifulSoup** [comment]
Good work, you're a time saver. @YongHuiLuo

**Comment by fatihcamuz** [comment]
I'm gonna examine that.. thanks

Fatih CAMUZ
14 Oca 2016 10:44 tarihinde "Tang Likang" <notifications@github.com> yazdı:

Good work, you're a time saver. @YongHuiLuo <https://github.com/YongHuiLuo>

—
Reply to this email directly or view it on GitHub
<https://github.com/ReactiveX/RxAndroid/issues/262#issuecomment-171573367>.

**Comment by 281922239** [comment]
Thanks for your sharing

**Comment by dimsuz** [comment]
Why is this issue still open? It looks more like some [strange] advertising of somebody developing his coding skills :)

**Comment by JakeWharton** [comment]
yeah we don't really have a good forum for this otherwise. Maybe the RxJava mailing list.

¯\\\_(ツ)_/¯

Thanks for sharing, but since there's no action to take I'm going to close.
