### ISSUE TITLE
Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by zhihuitang** [ReactiveX/RxAndroid#266]
> RxJavaPlugins.getInstance().registerErrorHandler(new RxJavaErrorHandler() {
>             @Override
>             public void handleError(Throwable e) {
>                 Log.w("test", "registerErrorHandler: " + e);
> 
>             }
>         });

I am using:
    compile 'io.reactivex:rxandroid:1.1.0'
    compile 'io.reactivex:rxjava:1.1.0'

I did add registerErrorHandler, but I still get exception and the App crash. Did I do something wrong?

> 
> 02-08 15:25:04.610 13481-13481/com.halebop.servicetips.dev D/HockeyApp: Writing unhandled exception to: /data/data/com.halebop.servicetips.dev/files/5839ca03-e2b9-4b5d-9d3a-344a468a4e90.stacktrace
> 02-08 15:25:04.615 13481-13481/com.halebop.servicetips.dev E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                              java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
>                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
>                                                                                  at android.os.Handler.handleCallback(Handler.java:615)
>                                                                                  at android.os.Handler.dispatchMessage(Handler.java:92)
>                                                                                  at android.os.Looper.loop(Looper.java:137)
>                                                                                  at android.app.ActivityThread.main(ActivityThread.java:4898)
>                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                                  at java.lang.reflect.Method.invoke(Method.java:511)
>                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
>                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
>                                                                                  at dalvik.system.NativeStart.main(Native Method)
>                                                                               Caused by: rx.exceptions.OnErrorNotImplementedException
>                                                                                  at rx.Observable$27.onError(Observable.java:7923)
>                                                                                  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
>                                                                                  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
>                                                                                  at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
>                                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
>                                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
>                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
>                                                                                  at android.os.Handler.handleCallback(Handler.java:615) 
>                                                                                  at android.os.Handler.dispatchMessage(Handler.java:92) 
>                                                                                  at android.os.Looper.loop(Looper.java:137) 
>                                                                                  at android.app.ActivityThread.main(ActivityThread.java:4898) 
>                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                                  at java.lang.reflect.Method.invoke(Method.java:511) 
>                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006) 
>                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773) 
>                                                                                  at dalvik.system.NativeStart.main(Native Method) 
>                                                                               Caused by: java.lang.reflect.UndeclaredThrowableException
>                                                                                  at $Proxy7.v2PersonPut(Native Method)
>                                                                                  at com.halebop.servicetips.utils.API.PersonAPI$1.call(PersonAPI.java:28)
>                                                                                  at com.halebop.servicetips.utils.API.PersonAPI$1.call(PersonAPI.java:25)
>                                                                                  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
>                                                                                  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
>                                                                                  at rx.Observable.unsafeSubscribe(Observable.java:8098)
>                                                                                  at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
>                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
>                                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
>                                                                                  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
>                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:137)
>                                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
>                                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
>                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
>                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
>                                                                                  at java.lang.Thread.run(Thread.java:856)
>                                                                               Caused by: javax.net.ssl.SSLException: Write error: ssl=0x58e80a68: I/O error during system call, Connection timed out
>                                                                                  at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_write(Native Method)
>                                                                                  at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:693)
>                                                                                  at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
>                                                                                  at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
>                                                                                  at libcore.net.http.FixedLengthOutputStream.flush(FixedLengthOutputStream.java:49)
>                                                                                  at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:130)
>                                                                                  at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
>                                                                                  at com.amazonaws.mobileconnectors.apigateway.ApiClientHandler.invoke(ApiClientHandler.java:91)
>                                                                                  at $Proxy7.v2PersonPut(Native Method) 
>                                                                                  at com.halebop.servicetips.utils.API.PersonAPI$1.call(PersonAPI.java:28) 
>                                                                                  at com.halebop.servicetips.utils.API.PersonAPI$1.call(PersonAPI.java:25) 
>                                                                                  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) 
>                                                                                  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) 
>                                                                                  at rx.Observable.unsafeSubscribe(Observable.java:8098) 
>                                                                                  at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) 
>                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
>                                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442) 
>                                                                                  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305) 
>                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
>                                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150) 
>                                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264) 
>                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
>                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
>                                                                                  at java.lang.Thread.run(Thread.java:856)

**Comment by dlew** [comment]
`RxJavaErrorHandler` also doesn't mask exceptions, it just allows you to handle them (in addition to whatever the subscriber is doing).

Also, `RxJavaErrorHandler` is not part of RxAndroid. The issue tracker is for bugs and features in RxAndroid. I suggest taking this question to a more appropriate forum, like the [RxJava discussion group](https://groups.google.com/forum/#!forum/rxjava) or [StackOverflow](http://stackoverflow.com/).
