### ISSUE TITLE
Observer manually call doOnnext()  or doOnCompleted()

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [ReactiveX/RxAndroid#267]
Hi, I'm trying to resolved the Observer after I get the response from a socket connection, I save the Observer into a Map and then I try to resolved this. Here is my code

    channel1.listen("hi", new Subscriber() {
                            @Override
                            public void onCompleted() {}

                            @Override
                            public void onError(Throwable e) {
                                Log.e("Error", e.getMessage());
                            }

                            @Override
                            public void onNext(Object o) {
                                Log.d("REsponse", o.toString());
                            }
                        }).then(new Subscriber<Object>() {
                            @Override
                            public void onCompleted() {Log.e("ONCOMPLETED", "");}
                            @Override
                            public void onError(Throwable e) {Log.e("ERROR", e.getMessage());}

                            @Override
                            public void onNext(Object o) {
                                Log.e("ONNEXT", o.toString());
                                channel1.broadcast("hi", payload, 2000);
                            }
                        });

My Idea is to call broadcast after I get the response from the socket connection, is any way of manually call onNext or onCompleted by getting the Observable?

**Comment by JakeWharton** [comment]
You can use a Subject to create an Observable that you can manually call onNext or onComplete on. Otherwise, your only choice is implementing a custom subscribe function which `Observable.create` takes.

Since this is a general usage question (and one not related to RxAndroid), I'm going to close. Feel free to hop onto the RxJava mailing list or ask your question on StackOverflow with the 'rxjava' tag.

**Comment by cesar-oyarzun-m** [comment]
sorry for posting here I will add the question in stackOverflow http://stackoverflow.com/questions/35301449/observable-rxandroid-resolved-manually
Do you have any code example of how to create a Subject?
