### ISSUE TITLE
I call observeOn(AndroidSchedulers.mainThread()) when there is no internet ,the app crash ,and the log just told me "E/AndroidRuntime: FATAL EXCEPTION: main".

### ISSUE THREAD

**Issue by lovejjfg** [ReactiveX/RxAndroid#271]
BaseDataManager.getDailyApiService().getLatestDailyStories()
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(new Action1<DailyStories>() {
                        @Override
                        public void call(DailyStories dailyStories) {
                            mView.onLoadMore(dailyStories);
                            mView.isLoading(false);
                            isLoading = false;
                        }
                    });

**Comment by iNoles** [comment]
Android's Log suppressed unknownhostexception

**Comment by artem-zinnatullin** [comment]
You need to pass error handler as second parameter to `subscribe()` or pass `Observer/Subscriber` to it. 

Issue is not related to `observeOn()` and RxAndroid. It's about usage of RxJava in general. 

Think of it like a `try/catch`, if you won't add it to place where `RuntimeException` may occur — it'll crash the app.
