### ISSUE TITLE
Cannot import rx.android.* for 1.1.0

### ISSUE THREAD

**Issue by captainbupt** [ReactiveX/RxAndroid#272]
When adding these two lines in gradle that imports rxandroid 1.1.0, I cannot import rx.android.* any more and AndroidSchedulers is no longer available either.

    compile 'io.reactivex:rxandroid:1.1.0'
    compile 'io.reactivex:rxjava:1.1.0'

This problem fixed when I downgrade rxandroid to 0.25.0 and lower.

Did you remove that package in the latest release?

**Comment by dlew** [comment]
There was a big change from RxAndroid 0.25.0 to 1.0. Most components got moved to smaller subprojects. You can read more about it here: http://blog.danlew.net/2015/09/01/how-to-upgrade-to-rxandroid-10/

`AndroidSchedulers` should still be in RxAndroid (in fact, that's just about all there is in here now). I believe it's just under a different package than before.
