### ISSUE TITLE
AndroidScheduler shared vs per-worker Handler

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxAndroid#275]
In the current `AndroidScheduler` code, a `Handler` is shared between all workers, and thus each task has to be tracked inside a Worker to remove them upon unsubscription.

I've been playing around with `Handler` for 2.x and I'd think this extra level of tracking could be avoided because the mass unsubscription is available via `handler.removeCallbacksAndMessages(null);`:

```java
static final class MainThreadWorker extends Worker {

    final Handler handler = new Handler(Looper.getMainLooper());

    volatile boolean disposed;

    @Override
    public Disposable schedule(Runnable run, long delay, TimeUnit unit) {
        if (disposed) {
            return EmptyDisposable.INSTANCE;
        }
        if (delay <= 0L) {
            handler.post(run);
        } else {
            handler.postDelayed(run, TimeUnit.MILLISECONDS.convert(delay, unit));
        }
        if (disposed) {
            handler.removeCallbacks(run);
            return EmptyDisposable.INSTANCE;
        }
        return () -> handler.removeCallbacks(run);
    }

    @Override
    public void dispose() {
        disposed = true;
        handler.removeCallbacksAndMessages(null);
     }
}
```

I'm not familiar with Android's performance profile but is there a penalty for having individual Handlers?

**Comment by JakeWharton** [comment]
`Handler` instances are fairly cheap since all they do is delegate to the underlying `Looper`. This sounds like a good strategy.
