### ISSUE TITLE
Add Scheduler which encapsulates a HandlerThread

### ISSUE THREAD

**Issue by tir38** [ReactiveX/RxAndroid#278]
I am trying to do some work that starts a `Handler` inside my Rx pipeline:

```
public void main() {
    Observable.just(1, 2, 3)
              .map(integer -> {
                  methodThatCreatesAHandler();
                  ...
              })
              ...
          .subscribe();
}

private void methodThatCreatesAHandler() {
    Handler handler = new Handler();
    handler.postDelayed(() -> {
        Log.d("TAG", "hello from the future");
    }, 1000);
}

````

If I subscribe on a plain Thread then I'll get an NPE because the thread doesn't have a Looper:

```
Observable.just(1, 2, 3)
          .map(integer -> {
              methodThatCreatesAHandler();
              return null;
          })
          .subscribeOn(Schedulers.newThread())
          .observeOn(AndroidSchedulers.mainThread())
          .subscribe();
```

So the README suggests creating a new Thread, setting up the Looper myself, creating a Handler, and then doing my work *inside* this thread.

```
public void main() {
    new Thread(new Runnable() {
        @Override
        public void run() {
            Looper.prepare();
            final Handler handler = new Handler(); // bound to this thread

            Observable.just(1, 2, 3)
                      .map(integer -> {
                          methodThatCreatesAHandler();
                          return null;
                      })
                      .subscribeOn(HandlerScheduler.from(handler))
                      .observeOn(AndroidSchedulers.mainThread())
                      .subscribe();

            // perform work, ...
            Looper.loop();
        }
    }, "custom-thread-1").start();
}
```

IMO this is pretty messy and requires a lot of boiler plate. I think we could rely on Android's existing `HandlerThread` to do all of this for us. I propose a new class `HandlerThreadSchedule` which manages all of this for us and allows us to subscribe like this:

```
Observable.just(1, 2, 3)
          .map(integer -> {
              methodThatCreatesAHandler();
              return null;
          })
          .subscribeOn(HandlerThreadSchedule.newHandlerThread())
          .observeOn(AndroidSchedulers.mainThread())
          .subscribe();
```

I've written this class here w/ a sample Activity to test it:
https://gist.github.com/tir38/4fa573cefe3ab041ab6889f4a4952921

So I have a few questions:

1. Is this something which fits inside the scope of this lib or should this be an extension in its own lib?
2. Did I miss some old discussion where this was considered and rejected? (I think I scanned all of the back issues about this and didn't see anything)

If this is of value I'll write some tests and create PR.

**Comment by JakeWharton** [comment]
What's the goal here? A Handler is just a light wrapper around a Looper
which operates on a single thread. Are you trying to do bits of work on
separate threads concurrently?

**Comment by tir38** [comment]
I currently have some code that creates a Handler which posts a delayed runnable. The work inside the delayed runnable is just a do-it-and-forget. I don't need to confirm that the work gets done. Nobody is waiting for the delayed runnable to finish.

I now want to wrap this code in my Rx pipeline and so I need to subscribe on a Thread that has a Looper.

**Comment by JakeWharton** [comment]
You can return an Observable from that code which uses timer() or delay()
for deferring its work and then flatMap that into the original stream.

**Comment by tir38** [comment]
Yeah I was hoping to not have to refactor that code, just to use it inside my Rx pipeline. It's in a separate library that I want to be usable whether the caller is using rx Java or not.

**Comment by JakeWharton** [comment]
What about using the main Looper for scheduling the action? Then the
callback can then use Rx to move the work to whatever thread it wants.

**Comment by JakeWharton** [comment]
Just re-read your initial issue... don't listen to the README. Its examples are terrible.

As to your actual use case here: does the method in question create a handler without passing in a `Looper`? Because that's a big anti-pattern in and of itself.

Observable is the unit of measure for asynchronous work and I don't see what the value in supporting this very specific and non-standard use case is in this library.

**Comment by tir38** [comment]
Yes, the `Handler` in the library just assumes that it's being executed on a `HandlerThread`.  That definitely needs to get fixed to make the lib more stable/usable.

In general though, what is this bad example trying to illustrate? https://github.com/ReactiveX/RxAndroid#observing-on-arbitrary-threads Why would anyone want to "bind asynchronous communication to an Android message loop using the Handler class"?

Thanks for taking the time to look this over and provide feedback.

**Comment by JakeWharton** [comment]
It's showing you can use any Handler as a Scheduler, not just one wrapped
around the main Looper.

**Comment by tir38** [comment]
so the TL;DR is that I might want to use some other Handler/Looper as a Scheduler. But the work I schedule *inside there* should still not assume that it has a Looper. It should either check for the existence of a looper: `new Hander(Looper.myLooper(), ...)` or it should  spool up it's own `HandlerThread`.

Glad to see this conversation at least influenced some changes for 2.x =)
