### ISSUE TITLE
How could implement sequence  requests in RXAndroid?

### ISSUE THREAD

**Issue by IskuhiSargsyan** [ReactiveX/RxAndroid#295]
I need to check if it exits in DB load and pass to view
if not 
load from Server ,Store in DB ,then pass to view
I confused in methods doOnNext(), flatMap() ,I don't which one to use

**Comment by JakeWharton** [comment]
This is a question specific to RxJava in general and not RxAndroid specifically. I would highly recommend you try the RxJava mailing list or StackOverflow with the rx-java tag instead. Not many people are active on the issues here and in general it's set up very poorly as a forum for offering help.
