### ISSUE TITLE
[Discussion] Code structure and convention

### ISSUE THREAD

**Issue by Yarikx** [ReactiveX/RxAndroid#30]
As I said in https://github.com/ReactiveX/RxAndroid/pull/25 I think we should discuss naming convention and code organization question.

Currently most of library functions is some kind of wrappers of native android components to lift them to use with Rx.
Some of them are using `from` prefix and name of wrapped component (`fromBroadcast`, `fromSharedPreferences`, etc). I think this is more verbose but it clear to the user what component is using under the hood.
Other wrappers just use simple form (like `clicks`, `input`). This is more pretty, but can confuse user for the first time.

Should we rename some of them to one kind?

**Comment by JakeWharton** [comment]
As part of #172 all of the inconsistent naming conventions have been removed. We will be absolutely mindful of this in the future as things get re-added. Consistency is a great thing!
