### ISSUE TITLE
CompositeSubscription class not found

### ISSUE THREAD

**Issue by 403462630** [ReactiveX/RxAndroid#304]
![nppnu9efvomu_v20 _ joi](https://cloud.githubusercontent.com/assets/8220219/16680510/935cfb7a-4521-11e6-891b-288d704eaa8e.png)

use genymotion and android SDK 4.4 below,  has this problem
use genymotion and android SDK  4.4 above, no this problem
I do not know why

**Comment by artem-zinnatullin** [comment]
Looks like you're using [multidex](https://developer.android.com/studio/build/multidex.html#mdex-pre-l), if so — make sure you're initializing it correctly: either extend `MultiDexApplication` or execute `MultiDex.install()` in `Application.attachBaseContext()`.

**Comment by 403462630** [comment]
@artem-zinnatullin  
oh yeah, It solves my problem, Thank you very mach.
