### ISSUE TITLE
Implement RxJavaHooks API for 1.1.7

### ISSUE THREAD

**Issue by iNoles** [ReactiveX/RxAndroid#306]
There is only one to use old API is in https://github.com/ReactiveX/RxAndroid/blob/f2103862639fa0483b5b8364fdd297bf1c432a28/rxandroid/src/main/java/rx/android/schedulers/LooperScheduler.java#L116

**Comment by JakeWharton** [comment]
The hooks are `@Experimental` and will be for quite a long time. Until they are stable they cannot be used by libraries.
