### ISSUE TITLE
How do I solve this issues?

### ISSUE THREAD

**Issue by a1018875550** [ReactiveX/RxAndroid#309]
rx.exceptions.OnErrorThrowable$OnNextValue
OnError while emitting onNext value: java.util.ArrayList.class
java.lang.IllegalStateException:Exception thrown on Scheduler.Worker thread. Add `onError` handling.
rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:112)
......
Caused by:
rx.exceptions.OnErrorThrowable$OnNextValue:OnError while emitting onNext value: java.util.ArrayList.class
rx.exceptions.Exceptions.throwOrReport(Exceptions.java:193)
rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:83)
rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
rx.Subscriber.setProducer(Subscriber.java:209)
rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
rx.Subscriber.setProducer(Subscriber.java:205)
rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
rx.Observable.unsafeSubscribe(Observable.java:9861)
rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$1.call(EventLoopsScheduler.java:172)
rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
java.util.concurrent.FutureTask.run(FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)

look the detail :http://bugly.qq.com/share/xemCV5

**Comment by artem-zinnatullin** [comment]
This is problem in your code, looks like you're throwing exception in `doOnEach()`. You either need to fix code in `doOnEach()` or add error handling.

**Comment by a1018875550** [comment]
but I don't use the `doOnEach()` in my code

**Comment by a1018875550** [comment]
what circumstances will throw this Exception?

**Comment by a1018875550** [comment]
thanks
