### ISSUE TITLE
Help with push notifications with Firebird

### ISSUE THREAD

**Issue by andresgmh** [ReactiveX/RxAndroid#319]
Hi there.

I speak spanish, I will try speak a good english OK? I need support. I have a client that needs develop push notification with ReactiveX and Firebird to an Android app. Please let me know if you have any complete documentation about how to do it or maybe, can you provide me your development services? Please let me know ASAP.

My email address is: andresgmh@gmail.com

Regards,

**Comment by JakeWharton** [comment]
These issues are only for tracking bugs and feature requests. This is not a commercial product offering support nor an appropriate place to seek help. We recommend the RxJava mailing list or StackOverflow for questions, links for which are in the README.
