### ISSUE TITLE
Question. PublishSubject - Why isn't there onStart() method?

### ISSUE THREAD

**Issue by rusmichal** [ReactiveX/RxAndroid#323]
Why isn't there onStart() method in PublishSubject, BehaviorSubject etc?

**Comment by JakeWharton** [comment]
Those types are not a part of RxAndroid. You want https://github.com/ReactiveX/RxJava.

**Comment by JakeWharton** [comment]
Also general usage questions are best asked on the mailing list or StackOverflow per the README of both projects.
