### ISSUE TITLE
android.os.StrictMode$InstanceCountViolation: when subscribing to an Observable from()

### ISSUE THREAD

**Issue by MinaSamy** [ReactiveX/RxAndroid#325]
Hello,

I'm testing my app in strict mode, in one of the activities that has a subscription object, I receive the following when navigating back to the launcher activity.

> 09-05 17:55:19.666 30958-30958/net.minasamy.reactiveprogrammingdemo E/StrictMode: class net.minasamy.reactiveprogrammingdemo.AppListActivity; instances=2; limit=1
>                                                                                   android.os.StrictMode$InstanceCountViolation: class net.minasamy.reactiveprogrammingdemo.AppListActivity; instances=2; limit=1
>                                                                                       at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
1. Open the app, click the card view item in the "Demo" tab.
2. The AppListActivity opens, press the back button.
3. Click the card view item again, navigate back you'll find the above output in the log.

The application source code is available here https://github.com/MinaSamy/ReactiveDemo.git

The error doesn't appear if I remove the Subscription object from the activity. it seems that there is a memory leak. I've tested the scenario on an API 23 emulator.

**Comment by JakeWharton** [comment]
What makes you think this is a problem with the RxAndroid library?

**Comment by MinaSamy** [comment]
The issue has something to do with Subscription object, when I remove it from the activity the issue doesn't happen, do you have any suggestions?

**Comment by JakeWharton** [comment]
RxAndroid's code removes posted messages from the handler's looper when you unsubscribe. Without a concise sample demonstrating that somehow we're leaking the reference it's likely a "normal" RxJava leak which can happen for all kinds of reasons. You can use tools like LeakCanary to isolate the leak and then operators like `onTerminateDetach()` to control how long-lived references are held.
