### ISSUE TITLE
Rename project to avoid misunderstanding? [Discussion]

### ISSUE THREAD

**Issue by Yarikx** [ReactiveX/RxAndroid#328]
As I can see 80% of issues for this project are not really related to it. 
Most of them are more related to RxJava, the other part is related to third party 'android Rx wrapper' libraries.

In the community, there are a lot of questions like 'What should I include RxAndroid or RxJava', or ' 'what is the difference between RxAndroid and RxJava'. For newbies, it's not so straightforward to understand what particular features RxAndroid provide. 

Back in the times when RxAndroid was a subproject of RxJava, RxAndroid contained a lot of different wrappers around Android API. But now library only contains Android handler scheduler and tools around it and all other wrappers are in third-party libraries.

So what about renaming this project for 2.0 to something like `RxAndroidSchedulers`?
- It should be much more descriptive from the name what this library provides.
- Fewer questions about 'Why feature X is not implemented?'

**Comment by JakeWharton** [comment]
The project is not limited to just schedulers. `MainThreadSubscription` is for creating observables, for example. And there's no restriction on more things being added other than they have to be widely useful for making RxJava on Android work.

The readme is clear on what the project is. We can add a message when creating an issue reiterating that they're likely filing an issue on the wrong project.

As someone who manages quite a few open source projects I can say that this project actually gets less off-topic and incorrect issues than most. The name of the project, the length and quality of its readme, and even putting messages in the issue creation box will not prevent people from creating these off-topic and incorrect issues.

I'm against renaming.

**Comment by Yarikx** [comment]
I don't suggest particularly `RxAndroidSchedulers` name, but still, all of the current functionality of RxAndroid is around Android threading model.

I see your point about not limiting this project only to Schedulers.
However, I think it's unlikely that any other functionality will become so widely used to be included in RxAndroid. Except maybe some new API for future android versions that will become necessary to add, but that's unlikely too.

For me `RxAndroid` is a very ambitious name as for the project that only provides Android thread related logic. I understand that it was pioneer project where all rx-android related code was born.

**Comment by JakeWharton** [comment]
> For me RxAndroid is a very ambitious name as for the project that only provides Android thread related logic.

It would be were it some random project on GitHub maintained by a random person. This is an official ReactiveX project providing the necessary types to make RxJava work on the Android platform and the naming convention is no different than any of the other projects under this organization.

**Comment by Yarikx** [comment]
Ok, got it.
Close this issue then, or leave it for further discussion.

**Comment by JakeWharton** [comment]
No comments in a month. Going to close for now.
