### ISSUE TITLE
Error:The modules 'RxAndroid', 'rxandroid-root' point to same directory in the file system

### ISSUE THREAD

**Issue by kfikani** [ReactiveX/RxAndroid#331]
I'm getting the following error as soon as I import the project to Android Studio.

Here is the full error:

```
Error:The modules 'RxAndroid', 'rxandroid-root' point to same directory in the file system.
Each module has to have a unique path.
Error:(10, 0) No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.
```

The second error points to this line in gradle:

`apply plugin: 'com.github.dcendents.android-maven'`

I've tried both branches 1.x and 2.x and got the same errors.

Any ideas on how to fix this problem?

**Comment by kfikani** [comment]
Ok so this error shows up when using gradle:2.1.3. I reverted back to gradle:2.1.0 and worked fine. Any plans to support 2.1.3?

**Comment by NikoYuwono** [comment]
Might be similar problem to this https://github.com/square/assertj-android/issues/174

Try to delete your old .iml file and reimport from Android Studio.

**Comment by kfikani** [comment]
yeh that worked thx!

**Comment by jimandreas** [comment]
See also: 

[https://code.google.com/p/android/issues/detail?id=219692#c16](https://code.google.com/p/android/issues/detail?id=219692#c16)

Fix at step 16 in this bug report worked for me. Change this line as follows:

    // classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
       classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'

in the rxandroid/build.gradle file.
