### ISSUE TITLE
RxAndroid 1.x and RxAndroid 2.x cannot be a depedency at the same time (in Android Studio 2.2.0?)

### ISSUE THREAD

**Issue by Xylez01** [ReactiveX/RxAndroid#334]
Hi,

First of all, I'm not sure if this issue belongs here. If thats the case, please let me know.
Yes, weird issue, but here goes. These are my dependencies:

```
compile 'io.reactivex.rxjava2:rxandroid:2.0.0-RC1'
compile 'io.reactivex.rxjava2:rxjava:2.0.0-RC3'

compile 'io.reactivex:rxandroid:1.2.1'
compile 'io.reactivex:rxjava:1.1.6'
```

When compiling this I get the following error during compilation:

```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForCurrentDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/rxjava.properties
    File1: C:\.gradle\caches\modules-2\files-2.1\io.reactivex.rxjava2\rxjava\2.0.0-RC3\53ee0863c48a13760b2ea44645a68293804d9cd0\rxjava-2.0.0-RC3.jar
    File2: C:\.gradle\caches\modules-2\files-2.1\io.reactivex\rxjava\1.1.6\2586312cd2b8a511e4c6236736f5a039fc0f2273\rxjava-1.1.6.jar
```

I could resolve this by adding `packagingOptions` in my `build.gradle`

```
packagingOptions {
    exclude 'META-INF/rxjava.properties'
}
```

I did not have this issue with an older version of Android Studio, but that just seems so unlikely. My android build tools is `com.android.tools.build:gradle:2.1.3`.

**Comment by JakeWharton** [comment]
This file comes from RxJava, not RxAndroid. Your workaround is correct.

**Comment by akarnokd** [comment]
I'm not sure if we can or should suppress creating that file in RxJava. Use the workaround as we don't use it.

**Comment by Xylez01** [comment]
You guys are lightning fast, thanks for the feedback.

**Comment by medvednic** [comment]
I'm in the same situation because [RxAndroidBle](https://github.com/Polidea/RxAndroidBle) uses [RxJava1](https://github.com/Polidea/RxAndroidBle/issues/72) and I used the same workaround to solve the issue.
Just to make sure - having both libraries should cause any problems?

Thanks,

**Comment by artem-zinnatullin** [comment]
>Just to make sure - having both libraries should cause any problems?

No, except that it'll increase method count.
