### ISSUE TITLE
Critical Error: missed onNext event

### ISSUE THREAD

**Issue by MaksTuev** [ReactiveX/RxAndroid#340]
When subscribe to observable which emits onNext event and then emits onError event from background thread to main thread when activity starting -> onNext event miss. https://github.com/MaksTuev/RxAndroid-bug - show, how you can repeat this bug

**Comment by JakeWharton** [comment]
I have a hard time seeing how RxAndroid plays any part. My guess would be that RxJava is skipping the error forward and you end up racing the next event. File an issue on RxJava instead?

**Comment by akarnokd** [comment]
By default `observeOn` emits `onError` eagerly even if there are `onNext`s waiting. Use the `observeOn` overload with the `delayError` parameter.

**Comment by JakeWharton** [comment]
Thanks, @akarnokd!

**Comment by MaksTuev** [comment]
Thanks!
