### ISSUE TITLE
RxAndroid in conjunction with RxJava 2

### ISSUE THREAD

**Issue by programmerr47** [ReactiveX/RxAndroid#348]
Hello. 

Recently rxJava 2 [has been released](https://github.com/ReactiveX/RxJava/releases/tag/v2.0.0).
So currently when I try to use rxAndroid 1.2.1 with rxJava 2.0.0:

```java
observable
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
```

I'm getting an error:

> **observeOn(io.reactivex.Schedulers)** in **Observable** cannot be applied to **(rx.Scheduler)**

I suppose it is because in rxJava 2 Schedulers was moved from **rx** package to **io.reactivex** package.

My question is, how I can use rxAndroid in conjunction with rxJava 2?

Thank you.

**Comment by xubuhang** [comment]
@programmerr47 @JakeWharton @mttkay Hello，How do I solve this problem ？

**Comment by programmerr47** [comment]
@xubuhang Hi. Simple: compile 'io.reactivex.rxjava2:rxandroid:2.0.0'
 It was my mistake that I didn't search a little bit before posting this issue

**Comment by xubuhang** [comment]
look here
<img width="492" alt="qq20161109-2 2x" src="https://cloud.githubusercontent.com/assets/4189632/20131043/c7afb28e-a695-11e6-855b-2dbb9b1d1baf.png">
<img width="1132" alt="qq20161109-1 2x" src="https://cloud.githubusercontent.com/assets/4189632/20131047/d51be672-a695-11e6-9023-a749e7b06658.png">
<img width="605" alt="qq20161109-3 2x" src="https://cloud.githubusercontent.com/assets/4189632/20131095/3f72fb50-a696-11e6-927c-a500385f4eec.png">

**Comment by viethoa** [comment]
Still have the same problem with io.reactivex.rxjava2:rxandroid:2.0.0. This is not solve the error *observeOn(io.reactivex.Schedulers) in Observable cannot be applied to (rx.Scheduler)*

**Comment by dimsuz** [comment]
@viethoa  You have a wrong import - `rx.Scheduler` is a scheduler from rxjava1, you need to import one from `io.reactivex`

**Comment by replyashu** [comment]
@programmerr47 @JakeWharton @mttkay
Still getting error io.reactivex.rxjava2:rxandroid:2.0.1. This does not solve the error observeOn(io.reactivex.Schedulers) in Observable cannot be applied to (rx.Scheduler)

**Comment by JakeWharton** [comment]
You're using the wrong import for AndroidSchedulers

**Comment by replyashu** [comment]
@JakeWharton :
 import io.reactivex.android.schedulers.AndroidSchedulers;
import io.reactivex.disposables.CompositeDisposable;
import io.reactivex.schedulers.Schedulers;

These are my imports

**Comment by JakeWharton** [comment]
You have a 1.x observable and are trying to use a 2.x scheduler

**Comment by buddhasaikia** [comment]
Your import for Observable should be `import io.reactivex.Observable;` not `import rx.Observable;`

**Comment by replyashu** [comment]
@JakeWharton apology, it was import in another file, which was being reflected here. Thanks for the prompt reply. And hats off to your contribution in RxJava and other libraries

**Comment by ku4irka** [comment]
@JakeWharton @bs2015 @dimsuz 
If I choose to import io.reactivex.Observable; then I have a problem with Subscription
![image](https://cloud.githubusercontent.com/assets/9765147/23874295/b7f880fa-083d-11e7-89a5-80fe91aa26eb.png)

**Comment by akarnokd** [comment]
@ku4irka In 2.x, the `Observer` requires `Disposable` and `Disposables` is the utility class to create some default instances.

**Comment by ku4irka** [comment]
@akarnokd please can show the example code, because i do not fully can understand you

**Comment by akarnokd** [comment]
```java
import io.reactivex.*;
import io.reactivex.disposables.*;

Disposable disposable = Disposables.empty();

disposable = io.reactivex.Observable.just(1).subscribeWith(new DisposableObserver<Integer>() {
    // ...
});
```

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#subscriber

**Comment by ku4irka** [comment]
@akarnokd Thanks for the advice
have a good day  :)

**Comment by trinadhkoya** [comment]
re check the import !! it should be as  @replyashu  said.

**Comment by mastermj94** [comment]
i had this problem too and my mistake , i was using wrong imports for rxjava2 so i changed my imports to:
`
import io.reactivex.Observer;`
`import io.reactivex.android.schedulers.AndroidSchedulers;`
`import io.reactivex.disposables.Disposable;`
`import io.reactivex.schedulers.Schedulers;
`
i hope this can help.
