### ISSUE TITLE
observeOn(rx.Scheduler) in Observable cannot be applied to (io.reactivex.Schedulers).

### ISSUE THREAD

**Issue by xubuhang** [ReactiveX/RxAndroid#349]
look here
<img width="492" alt="qq20161109-2 2x" src="https://cloud.githubusercontent.com/assets/4189632/20131043/c7afb28e-a695-11e6-855b-2dbb9b1d1baf.png">
<img width="605" alt="qq20161109-3 2x" src="https://cloud.githubusercontent.com/assets/4189632/20131095/3f72fb50-a696-11e6-927c-a500385f4eec.png">
I import compile 'io.reactivex.rxjava2:rxjava:2.0.0' and compile 'io.reactivex.rxjava2:rxandroid:2.0.0'，but observeOn(rx.Scheduler) in Observable cannot be applied to (io.reactivex.Schedulers). why？How do I solve this problem ？ @JakeWharton @mttkay @benjchristensen

**Comment by akarnokd** [comment]
Hi. You have probably `import rx.*` or `import rx.Observable` somewhere in that file that picks the 1.x `Observable`.

**Comment by JakeWharton** [comment]
Or, if you wanted the opposite, you have the wrong AndroidSchedulers imported.

**Comment by xubuhang** [comment]
I've realized my false .
import io.reactivex.Observable;
import io.reactivex.Observer;
import io.reactivex.android.schedulers.AndroidSchedulers;
import io.reactivex.schedulers.Schedulers;
import okhttp3.ResponseBody;
import retrofit2.http.Field;
import retrofit2.http.FormUrlEncoded;
import retrofit2.http.GET;
import retrofit2.http.POST;
import retrofit2.http.Query;
