### ISSUE TITLE
CompositeException breaks Serializable 

### ISSUE THREAD

**Issue by chaviw** [ReactiveX/RxAndroid#353]
CompositeException is not really Serializable because of the inner static class `PrintStreamOrWriter` which is not Serializable. The app will crash if you try to send a CompositeException through an Intent or add it to a bundle via `putSerializable()`

This might be more for RxJava where the actual CompositeException is, but it breaks on Android.

**Comment by JakeWharton** [comment]
This class is not from RxAndroid but RxJava. You can file an issue on its project.
