### ISSUE TITLE
outofmemory error

### ISSUE THREAD

**Issue by ijustyce** [ReactiveX/RxAndroid#356]
In the last week I start use rxjava and rxandroid in our app, but met a lots crash, here is the log   

#1 main
java.lang.OutOfMemoryError
pthread_create (1040KB stack) failed: Out of memory
解析原始
}
1 java.lang.Thread.nativeCreate(Native Method)
2 java.lang.Thread.start(Thread.java:1078)
3 java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
4 java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1556)
5 java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:310)
6 java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:527)
7 java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:626)
8 rx.internal.c.r.b(NewThreadWorker.java:244)
9 rx.internal.c.e.a(CachedThreadScheduler.java:222)
10 rx.internal.c.e.a(CachedThreadScheduler.java:212)
11 rx.internal.a.w.a(OperatorSubscribeOn.java:45)
12 rx.internal.a.w.a(OperatorSubscribeOn.java:30)
13 rx.internal.a.i.a(OnSubscribeLift.java:48)
14 rx.internal.a.i.a(OnSubscribeLift.java:30)
15 rx.k.a(Observable.java:10236)
16 rx.k.b(Observable.java:10203)
17 rx.k.b(Observable.java:10008)
18 com.ijustyce.fastandroiddev.d.f.c(HttpResponse.java:90)
19 com.ijustyce.fastandroiddev.d.f.a(HttpResponse.java:28)
20 com.ijustyce.fastandroiddev.d.n.a(HttpResponse.java:173)
21 com.ijustyce.fastandroiddev.d.n.a(HttpResponse.java:158)
22 com.android.a.a.o.d(StringRequest.java:67)
23 com.android.a.a.o.b(StringRequest.java:30)
24 com.android.a.i.run(ExecutorDelivery.java:99)
25 android.os.Handler.handleCallback(Handler.java:743)
26 android.os.Handler.dispatchMessage(Handler.java:95)
27 android.os.Looper.loop(Looper.java:150)
28 android.app.ActivityThread.main(ActivityThread.java:5546)
29 java.lang.reflect.Method.invoke(Native Method)
30 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
31 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

and here is my code 
 Observable.create(new Observable.OnSubscribe<Void>() {
            @Override
            public void call(Subscriber<? super Void> subscriber) {
                if (cacheTime < 0 || StringUtils.isEmpty(response)) return;
                responseData.put(cacheKey, DateUtil.getTimesTamp() + response);
                FileUtils.writeTextFile(file, IJson.toJson(cacheModel, CacheModel.class));
            }
        }).subscribeOn(Schedulers.io()).observeOn(Schedulers.io()).subscribe();

I really don't know how to fix it, please help , thinks in advance .

**Comment by JakeWharton** [comment]
This is not a problem with RxAndroid nor even RxJava. You have a memory leak of some sort that's consuming all your app's memory.
