### ISSUE TITLE
Can't use AndroidSchedulers.mainThread() after migrating to RxJava2?

### ISSUE THREAD

**Issue by AruLNadhaN** [ReactiveX/RxAndroid#357]
After migrating to RxJava2. observeOn doesn't accept `AndroidSchedulers`.
Is there a alternate in Schedulers for AndroidSchedulers.mainThread() or how should i solve this issue ?

OLD versions 
RxAndroid - 1.2.1
RxJava - 1.1.6

Migrated Versions
RxAndroid - 2.0.1
RxJava - 2.0.3

```
 rxHelper.manageSubscription(
                mDataManager.getProducts()
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeOn(Schedulers.io())
                .subscribe(new SingleSubscriber<List<Items>>() {
                    @Override
                    public void onSuccess(List<Items> products) {
                        getView().hideProgress();
                        if (!products.isEmpty()) {
                            getView().showText(String.valueOf(products.get(0).getName()));
                            getView().showItems(products);
                        } else {
                            getView().showEmpty();
                        }
                    }

                    @Override
                    public void onError(Throwable error) {
                        Timber.e(error, "There was an error retrieving the products");
                        getView().hideProgress();
                        getView().showError();
                    }
                })
        );
```

**Comment by artem-zinnatullin** [comment]
This has nothing to do with order. Just use 2.x branch of RxAndroid https://github.com/ReactiveX/RxAndroid/blob/2.x/README.md#binaries

**Comment by AruLNadhaN** [comment]
I'm already using 2.x branch. These are my dependencies.
```
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.0.3'
```
![rx](https://cloud.githubusercontent.com/assets/5804413/21581427/da0e24f6-d057-11e6-8533-7e7d2c813e07.PNG)

**Comment by akarnokd** [comment]
Something else could still import RxJava 1 and you use that API. RxJava 1 and 2 are not binary compatible and v2 is not a drop-in replacement. You have to update your imports and change certain class and method names. See the [wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0) for futher details.

**Comment by artem-zinnatullin** [comment]
Try fully qualified name,  I believe you have import of v1 in this Java
file.

**Comment by JakeWharton** [comment]
Yep. You're importing the wrong class as Artem said. Correct the import or use the fully qualified name to point at the 2.x version of this class.

**Comment by Buggyy** [comment]
Try   

> compile 'io.reactivex:rxandroid:1.2.1'
> compile 'io.reactivex:rxjava:1.1.6'

**Comment by ronanhardiman** [comment]
the same error:
`compile 'io.reactivex.rxjava2:rxjava:2.1.1'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'`
try
`compile 'io.reactivex.rxjava2:rxjava:2.1.0`

**Comment by beblank** [comment]
same error
compile "io.reactivex.rxjava2:rxjava:2.1.1"
compile 'io.reactivex.rxjava2:rxandroid:2.0.1'

bugs gone
use import io.reactivex.Observable

**Comment by beblank** [comment]
use Observable from io.reactivex.Observable

**Comment by sarathraj-coder** [comment]
This is working  
    // RX
    rxjava2_version = '2.0.1'
    compile "io.reactivex.rxjava2:rxjava:$rxjava2_version"
    compile "io.reactivex.rxjava2:rxandroid:$rxjava2_version"

and sample  code is 

  import statements are 
    
            import io.reactivex.Observable;
            import io.reactivex.android.schedulers.AndroidSchedulers;
            import io.reactivex.disposables.Disposable;
            import io.reactivex.functions.Function;
            import io.reactivex.schedulers.Schedulers;

Sample Async 

           private void applyDiscount(String order){
          Observable.just(order)
                .map(new Function<String, Boolean>() {
                    @Override
                    public Boolean apply(String order) throws Exception {
                        return null;
                    }
                })
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new io.reactivex.Observer<Boolean>() {
                    @Override
                    public void onSubscribe(Disposable d) {

                    }

                    @Override
                    public void onNext(Boolean value) {

                    }

                    @Override
                    public void onError(Throwable e) {

                    }

                    @Override
                    public void onComplete() {

                    }
                });
              }

**Comment by tir38** [comment]
Be careful with

```
rxjava2_version = '2.0.1'
compile "io.reactivex.rxjava2:rxjava:$rxjava2_version"
compile "io.reactivex.rxjava2:rxandroid:$rxjava2_version"
```

RxJava2 and RxAndroid(2) don't always deploy updates in-sync (e.g. right now latest RxJava is 2.1.3 but latest RxAndroid is 2.0.1)

**Comment by JakeWharton** [comment]
"don't always" --> "never"

**Comment by JakeWharton** [comment]
Well, except for 2.0.0! But yeah they're otherwise completely independently
versioned libraries.

**Comment by abiemann** [comment]
**replace**
import rx.Observable;
**with**
import io.reactivex.Observable;

**Comment by aakashbhusal7** [comment]
its not working..i get the error: cannot resolve method subscribeOn(rx.scheduler)

package com.example.abhus.listingapp.Presenter;

import com.example.abhus.listingapp.asset.JsonService;
import com.example.abhus.listingapp.model.Post;
import com.example.abhus.listingapp.views.DetailedActivity;

import rx.Observer;
import rx.android.schedulers.AndroidSchedulers;
import rx.schedulers.Schedulers;

public class DetailPresenter {
    DetailedActivity mView;
    JsonService mForum;

    public DetailPresenter(DetailedActivity activity, JsonService forum) {

        mView = activity;
        mForum = forum;
    }
    public void loadPost() {

        mForum.getApi()
                .getPost(mView.getPostId())
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<Post>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(Throwable e) {

                    }

                    @Override
                    public void onNext(Post post) {

                        mView.displayPost(post);
                    }
                });
    }

**Comment by beblank** [comment]
replace
import rx.Observable;
with
import io.reactivex.Observable;

**Comment by AnuraagPatil** [comment]
Go back to 

Old Versions

    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.reactivex:rxjava:1.1.6'

Then to the Newer Version:

    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.1.1'

Sounds Wierd but it works

**Comment by rifanalam** [comment]
> Go back to
> 
> Old Versions
> 
> ```
> compile 'io.reactivex:rxandroid:1.2.1'
> compile 'io.reactivex:rxjava:1.1.6'
> ```
> Then to the Newer Version:
> 
> ```
> compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
> compile 'io.reactivex.rxjava2:rxjava:2.1.1'
> ```
> Sounds Wierd but it works

After clean project what will happen ?

**Comment by pablorcruh** [comment]
This  version worked for me

    implementation "io.reactivex.rxjava3:rxjava:3.0.0-RC3"
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
