### ISSUE TITLE
toMap for Arraymap

### ISSUE THREAD

**Issue by kagile** [ReactiveX/RxAndroid#359]
Is there any way to create ArrayMap instead of HashMap using toMap() in RxJava or RxAndroid?

**Comment by JakeWharton** [comment]
This is a question for RxJava, not RxAndroid. The answer will be that you need to implement it yourself though, because there's no map factory abstraction in RxJava.

**Comment by dimsuz** [comment]
I remember that I used `collect()` operator for this, something like

```java
observable.collect(() -> new ArrayMap<K,V>(), (map, v) -> map.put(toKey(v), toValue(v))
```

(you decide what `toKey()`, `toValue()` do)

**Comment by kagile** [comment]
@dimsuz thanks. `collect()` works fine.
