### ISSUE TITLE
Port setMainThreadSchedulerHandler API to 1.x

### ISSUE THREAD

**Issue by david-becher** [ReactiveX/RxAndroid#361]
Hey there,

is it possible (to simplify JUnit Testing of RxJava functionality with Android) to port the `setMainThreadSchedulerHandler` API (don't know which other functions should be accompanying this specific method call) also to the 1.x branch and prepare a new release? It's currently only being present in the 2.x branch of RxAndroid.

The equivalent API (e.g. `RxJavaHooks.setOnComputationScheduler`) is also present in RxJava 1.1.9, so isn't it only logical to port this equivalent functionality to RxAndroid's 1.x branch?

This would make it really simple to unit test parts of android apps which are calling `AndroidSchedulers.mainThread()`.

**Comment by isfaaghyth** [comment]
Hi!

maybe you can suggest for the next version. check this out https://github.com/ReactiveX/RxAndroid/commit/5cb239130dceab95797b7313b19f2d8e95407d8f

thanks!

**Comment by ZacSweers** [comment]
RxJava 1.x has reached EoL. Would recommend updating or using `RxJavaInterop` to share the RxAndroid 2.x scheduler with RxJava 1
