### ISSUE TITLE
Multi process

### ISSUE THREAD

**Issue by kartheek222** [ReactiveX/RxAndroid#363]
I am working on an application where my service runs in a different process. 
Does RxAndroid supports communication between the service running one process(A) and the application components running on different process(B).

**Comment by artem-zinnatullin** [comment]
RxJava and RxAndroid do not have built-in support for multi-process communication, but you definitely can build your own one using Rx with some IPC stack under the hood:

* Broadcasts
* Files
* Binders
* Sockets
* ContentProvider/ContentResolver
* Whatever
