### ISSUE TITLE
Android Library project throws java.lang.NoClassDefFoundError: Failed resolution of: Lrx/Observer;

### ISSUE THREAD

**Issue by byteground** [ReactiveX/RxAndroid#366]
Hi,
I have a library which makes use of Rx and I am packing this library as an aar which can be used in other projects. I am able to generate the aar but when I try to access it in other projects, it throws 
java.lang.NoClassDefFoundError: Failed resolution of: Lrx/Observer;

Caused by: java.lang.ClassNotFoundException: Didn't find class "rx.Observer" on path: DexPathList

Maybe I am writing the build.gradle wrong or not excluding some things. Any help is much appreciated. 

My library's build.gradle looks like this 

```
....
compile 'io.reactivex:rxandroid:1.0.1'
compile 'io.reactivex:rxjava:1.0.14'
...
```

**Comment by MarsXan** [comment]
I have the same issue

**Comment by ivandrag** [comment]
Hi,

Did you find any solution?

**Comment by byteground** [comment]
Hey Guys, the problem was that when the aar is generated locally it doesn't pack all the dependencies inside. That is by design!
You need to publish the aar to a maven repo and a pom file with all the dependencies listed, then gradle can get all the dependencies required.

**Comment by ivandrag** [comment]
Hi Chetan, Thanks for your answer. I will try what you did, but what temporary fixed the problem for me was downgrading the RxJava version to this one: `compile 'io.reactivex:rxjava:1.0.16'`
