### ISSUE TITLE
how to use RxAndroid2.X in Eclipse

### ISSUE THREAD

**Issue by wx2013** [ReactiveX/RxAndroid#368]
how to use RxAndroid2.X in Eclipse

**Comment by JakeWharton** [comment]
If you're asking how to import I have no idea. If you're asking how to use it as a dependency, I also have no idea. Both questions are probably more appropriate for StackOverflow. The project is built with and can be consumed by Gradle which is the official build system of Android and the project can be imported into Android Studio which is the official IDE of Android projects so those are the only two we explicitly support.
