### ISSUE TITLE
Error : 1.2.1 -> 2.0.1

### ISSUE THREAD

**Issue by sheep0704** [ReactiveX/RxAndroid#369]
'io.reactivex:rxandroid:1.2.1' 
升级
compile 'io.reactivex.rxjava2:rxandroid:2.0.1'

报错error:
Error:(10, 10) 错误: 程序包rx不存在
import rx.Observable;

**Comment by JakeWharton** [comment]
That class is no longer present in 2.x. Please read https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0 to learn about the new packages and classes.
