### ISSUE TITLE
Java 7

### ISSUE THREAD

**Issue by mttkay** [ReactiveX/RxAndroid#37]
Quick poll: anyone here who requires RxAndroid to support Java 6? It would be ideal if we could make a cut and drop Java 6 support. Any JARs built with language level 7 will NOT work with Android apps that are compiled against level 6, since Java 7 introduces new byte code instructions so is not backwards compatible.

The problem is that it's easy to miss that when juggling multiple SDKs and JVMs on your dev machine. I'm using jEnv right now to do that, but we already encountered an issue where a Nebula plugin was compiled and deployed under Java 7 and would fail the RxAndroid build.

Considering that Java 6 has reached end of life, should we support it or not? It's difficult to say, since it definitely took us a while to make the switch to Java 7 on Android.

**Comment by JakeWharton** [comment]
Another data point: JDK 7 is about to EOL.

Also this project won't see 1.0 for some time... #ShowMeTheDiamondOperator

**Comment by JakeWharton** [comment]
Do we still need to wait? JDK 6 was EOL'd 2 years ago and the tools have been supporting this for about two years. JDK 7 has been EOL'd as well so you really shouldn't even be using that anymore. There's absolutely not reason not to be using JDK 8 as your build JDK. Now, as the to Java version you are targeting, if you are not using 7 (or 8 w/retrolambda for the bold) then why?

**Comment by mttkay** [comment]
Fine by me.

**Comment by dlew** [comment]
:+1: to bumping the version.

**Comment by JakeWharton** [comment]
Fixed by #194.
