### ISSUE TITLE
Maven badge in readme points to wrong URL

### ISSUE THREAD

**Issue by tir38** [ReactiveX/RxAndroid#375]
In the README.md there's a maven central badge:

```
RxAndroid: 
<a href='http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.reactivex.rxjava2%22%20a%3A%22rxjava%22'>
<img src='http://img.shields.io/maven-central/v/io.reactivex.rxjava2/rxandroid.svg'>
```

I don't think this is linking to the right location on maven central.

**Comment by JakeWharton** [comment]
Looks right to me. Why do you think it's wrong?

**Comment by tir38** [comment]
I went back to look and the badge was pointing to rxandroid artifact and I thought I was losing my mind. Then I saw that @egor-n had fixed it.
