### ISSUE TITLE
I also encountered RxAndroid AndroidSchedulers.mainThread () problem

### ISSUE THREAD

**Issue by Huazhiling** [ReactiveX/RxAndroid#378]
I used rxjava in the project to add observeOn, but encountered a package wrong.
But I am in the gradle remote are dependent on the 2.x class library, I can not know where the problem
![image](https://cloud.githubusercontent.com/assets/22829887/26285397/70a67fa2-3e81-11e7-8a8f-3f47e3a6aa90.png)

Here is my gradle output information:
![image](https://cloud.githubusercontent.com/assets/22829887/26285400/92cfa68a-3e81-11e7-9a73-891aaf154d6c.png)

Thank you very much

**Comment by garr741** [comment]
I found two related posts that may help you out
[https://github.com/ReactiveX/RxJava/issues/5313](https://github.com/ReactiveX/RxJava/issues/5313)
[https://github.com/ReactiveX/RxAndroid/issues/348](https://github.com/ReactiveX/RxAndroid/issues/348)

**Comment by JakeWharton** [comment]
You're trying to use an RxAndroid 2.x with an RxJava 1.x scheduler. Either change the thing returning an observable to use RxJava 2.x, or change your import to use RxAndroid 1.x.

StackOverflow is a great place to ask questions about this as it's not a bug or feature request in this library.
