### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'boolean io.reactivex.internal.fuseable.SimpleQueue.isEmpty()' on a null object reference

### ISSUE THREAD

**Issue by ivnsch** [ReactiveX/RxAndroid#382]
I get this exception sometimes. It can't be reproduced reliably. it's related with rxandroid and can't find any reference to my code:

> 
>    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
>        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:113)
>        at android.os.Handler.handleCallback(Handler.java:751)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:154)
>        at android.app.ActivityThread.main(ActivityThread.java:6119)
>        at java.lang.reflect.Method.invoke(Native Method)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
>     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean io.reactivex.internal.fuseable.SimpleQueue.isEmpty()' on a null object reference
>        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
>        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
>        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
>        at android.os.Handler.handleCallback(Handler.java:751) 
>        at android.os.Handler.dispatchMessage(Handler.java:95) 
>        at android.os.Looper.loop(Looper.java:154) 
>        at android.app.ActivityThread.main(ActivityThread.java:6119) 
>        at java.lang.reflect.Method.invoke(Native Method) 
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 

Any ideas...?

**Comment by akarnokd** [comment]
This is not an RxAndroid issue per se and judging from the NPE location, I'd guess some (custom?) `Observable` you have violates the protocol. Please resubmit this issue on the [RxJava issue list](https://github.com/ReactiveX/RxJava/issues) and include the relevant code as well.

**Comment by ivnsch** [comment]
Ok, I'll submit it there, though I can't add any code, because it would have to be the complete code of my app, since I can't see what causes it...

**Comment by dengm129** [comment]
#382
