### ISSUE TITLE
Flowable request N was changed when using " .observeOn(AndroidSchedulers.mainThread())"

### ISSUE THREAD

**Issue by lengxf** [ReactiveX/RxAndroid#384]
Flowable request N was changed when using " .observeOn(AndroidSchedulers.mainThread())".

Please check the log .

![screenshot from 2017-07-24 16-14-15](https://user-images.githubusercontent.com/10055394/28514580-2949c094-7020-11e7-8eb3-a88d6ab0b48e.png)

what's reason do you know ? thanks.

**Comment by lengxf** [comment]
the library version :
    compile 'io.reactivex.rxjava2:rxjava:2.1.2'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'

**Comment by JakeWharton** [comment]
Not an RxAndroid issue and double-posted to RxJava anyway.
