### ISSUE TITLE
thread stack oom，caused by threadpool RxCachedThreadScheduler

### ISSUE THREAD

**Issue by Justin-Xu** [ReactiveX/RxAndroid#385]
the threads in threadpool RxCachedThreadScheduler cannot reuse, thread num grow per use, at last cause the thread stack oom. that is my problem.

**Comment by JakeWharton** [comment]
There is not enough information to make this report actionable, but it doesn't seem related to RxAndroid anyway. RxCachedThreadScheduler comes from RxJava. If you think there's a bug please file an issue on that project with a failing test case or sample code that reproduces the issue.
