### ISSUE TITLE
How to create an Oberservable for multiple/unsolicited messages?

### ISSUE THREAD

**Issue by suarezu** [ReactiveX/RxAndroid#389]
Hi all,

I know how to create an Observable for an HTTP RESTful response with RxAndroid or combined with  Retrofit, but have no idea for multiple/unsolicited messages like TCP/UDP receive(...)?

As a client, the receive(...) will be in a loop for continuous notification from a server, is it possible to create an Observable with which I can process the responses in the onNext? @JakeWharton please help show some clue or snippet if possible.

**Comment by akarnokd** [comment]
You should ask such questions on StackOverflow (and refrain from calling out specific contributors).
