### ISSUE TITLE
Unable to import whole repo into Android Studio

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ReactiveX/RxAndroid#399]
I get this error:

![image](https://user-images.githubusercontent.com/5357526/30519958-1be28aaa-9bac-11e7-8759-53e5399a49c3.png)

**Comment by artem-zinnatullin** [comment]
Can you please try to open the project with stable version of Android Studio, like 2.3.3?

**Comment by AndroidDeveloperLB** [comment]
Sorry no. I don't have it.
Also, note that if I change the gradle file to have this:

    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.1.3'

instead of this:

    compile project(':rxandroid')

-it works fine.

**Comment by JakeWharton** [comment]
You have to either use a stable version of AS or update the project to 3.0. Until 3.0 is stable, we require stick with the stable version.

**Comment by AndroidDeveloperLB** [comment]
The beta/alpha/preview versions of Android Studio are out there for a very long time. It should work...

**Comment by JakeWharton** [comment]
The length of time is irrelevant. It's not stable and thus unsupported.

**Comment by artem-zinnatullin** [comment]
If you change https://github.com/ReactiveX/RxAndroid/blob/eb832334da3f2feb9351350bdcc7748d36c4da20/build.gradle#L8 to Android Gradle Plugin 3.x, it should work with Android Studio 3.x.

And this is not related to users who consume the library as an external artifact.

**Comment by AndroidDeveloperLB** [comment]
ok ok.
Will it work when it becomes stable, though?

**Comment by artem-zinnatullin** [comment]
Yes.

What is your use case? You want to contribute to/change the project? Normally you consume RxAndroid as external dependency through build system like Gradle.

**Comment by AndroidDeveloperLB** [comment]
Why doesn't it work with the newest one, though? Bug in Gradle? In IDE?

**Comment by wbinarytree** [comment]
@AndroidDeveloperLB It's normal that alpha/beta version Android Studio can not download the source code of your dependencies .From a very long times ago I suppose.
