### ISSUE TITLE
[Question] Any plans to adding something like ViewObservable.pagerPageChanges()?

### ISSUE THREAD

**Issue by dimsuz** [ReactiveX/RxAndroid#40]
I am interested to know if there are any plans to create operators similar to `ViewObservable.clicks()` and `ViewObservable.itemClicks()` but for `ViewPager`, i.e. page changes, page scrolls etc.

Or is RxAndroid focused on core android libs and not trying to create ViewObservable helpers for all the stuff that might exist? :)

**Comment by kboyarshinov** [comment]
@dimsuz Any updates on that?

Just thought of WidgetObservable having something like:

    Observable<OnPageSelectedEvent> pageSelection(ViewPager pager);
    Observable<OnPageScrolledEvent> pageScroll(ViewPager pager);
    Observable<OnPageScrollStateChangedEvent> pageScrollState(ViewPager pager);

**Comment by dimsuz** [comment]
Nope, so far I didn't have time to try doing any of this... You can try if you have :)
