### ISSUE TITLE
About size of apps using RxAndroid

### ISSUE THREAD

**Issue by pellyadolfo** [ReactiveX/RxAndroid#405]
Hi, I am considering either adding a FSM to my app or basing it on RxAndroid.

What really discourages me about RxAndroid, is the oversize required by RxJava itself.

So I would like to hear your experiences in size increase using RxAndroid as a base framework including compression with ProGuard.

Thanks

**Comment by JakeWharton** [comment]
This forum is for bug reports and feature requests only. Please ask general usage questions on StackOverflow or the RxJava mailing list.

**Comment by Jenn2476** [comment]
So if I'm seeing a issue with my Insta Shopper app where do I go to ask for help with iasue?
