### ISSUE TITLE
AndroidSchedulers.from() doesn't work in IntentService

### ISSUE THREAD

**Issue by Delphian2015** [ReactiveX/RxAndroid#413]
Hello.  I am trying to use the next code in IntentService:

```
mRepository.getInfo()
                       .retryWhen(new RetryWithDelay(5,5000,AndroidSchedulers.from(Looper.myLooper())))
                        .subscribeWith(new DisposableMaybeObserver<String>() {}
 
public class RetryWithDelay implements Function<Flowable<Throwable>, Publisher<?>> {

    private final int maxRetries; // the quantity of the same requests
    private final long retryDelayMillis; // delay between two requests
    private int retryCount;
    private Scheduler scheduler;

    public RetryWithDelay(final int maxRetries, final int retryDelayMillis) {
        this.maxRetries = maxRetries;
        this.retryDelayMillis = retryDelayMillis;
        this.retryCount = 0;
    }

    public RetryWithDelay(final int maxRetries, final int retryDelayMillis, Scheduler scheduler) {
        this.maxRetries = maxRetries;
        this.retryDelayMillis = retryDelayMillis;
        this.retryCount = 0;
        this.scheduler = scheduler;
    }
    @Override
    public Publisher<?> apply(Flowable<Throwable> throwableFlowable) throws Exception {
        return throwableFlowable.flatMap(new Function<Throwable, Publisher<?>>() {
            @Override
            public Publisher<?> apply(Throwable throwable) throws Exception {
                if (++retryCount < maxRetries) {
                    // When this Observable calls onNext, the original
                    // Observable will be retried (i.e. re-subscribed).
                    if(scheduler==null) {
                        return Flowable.timer(retryDelayMillis,
                                TimeUnit.MILLISECONDS);
                    }else{
                        return Flowable.timer(retryDelayMillis,
                                TimeUnit.MILLISECONDS, scheduler);
                    }
                }

                // Max retries hit. Just pass the error along.
                return Flowable.error(throwable);
            }
        });
    }
}
```

I need to execute retryWhen method in IntentService thread. if i am using  RetryWithDelay constructor without Scheduler everything works well, but retryWhen uses RxJava thread, but when i add AndroidSchedulers.from(Looper.myLooper()) nothing works. The timer method doesn't work and doesn't produce errors. mRepository.getInfo() method doesn't use subscribeOn and observeOn.

**Comment by JakeWharton** [comment]
I don't see how this can work. An `IntentService` work is required to be synchronous as it will interpret the return of `onHandleIntent` as completion and stop the service. If you need to handle retry you should be using something like `JobScheduler` or `JobIntentService`.

But, moreover, this isn't a problem with RxAndroid itself, as the creation of the scheduler is working correctly.

**Comment by Delphian2015** [comment]
I need to handle SocketTimeoutException using RxJava and RxAndroid stack. But I have a lot of requests that is why i am using IntentService. Is there any way to repeate a request using Rx methods in intentService thread?  JobIntentService in this situation, nothing will decide

**Comment by JakeWharton** [comment]
Schedule another intent to be sent to the service to trigger it again after
the desired delay.

**Comment by Delphian2015** [comment]
Jake, thank you. But in my situation it's unreal. I can do all methods with IntentService + httpUrlconnection but  I  wan't to return to the old paradigm. I really like Rx! I am trying to find the decision using retrofit2 methods. Maybe it helps. it strange but on the network I didn't see examples of  using Rx in long-term operations and this is also an important issue.

**Comment by Joesta** [comment]
Hi Jake, if you have a bound service that generates large amount of data and sends it to subscribed components, what are the benefits of using AndroidSchedulers.from(looper) over AndroidSchedulers.mainThread() in the Service? 
![screenshot from 2019-02-07 14-59-32](https://user-images.githubusercontent.com/15924430/52413024-0ae46e80-2ae9-11e9-8f5b-be8234a35914.png)

{Looper looper = Looper.myLooper() instead of getMainLooper()}

**Comment by JakeWharton** [comment]
An intent service has its own looper because it operates on a background thread. For the main thread there's no reason to prefer your own scheduler over the provided one.
