### ISSUE TITLE
connot resolve RxJava2CallAdapterFactory.create()

### ISSUE THREAD

**Issue by mahdihp** [ReactiveX/RxAndroid#421]
connot resolve RxJava2CallAdapterFactory.create() from Using Retrofit 2:
```
 final Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(mainUrl)
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .build();
        return retrofit.create(tClass);

```
using of version in android: 
 implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'
    implementation 'io.reactivex.rxjava2:rxjava:2.1.12'
implementation 'com.google.code.gson:gson:2.8.2'
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'

**Comment by akarnokd** [comment]
You have to import the adapter: https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava2#download

**Comment by vanniktech** [comment]
Also this issue is on the wrong repository.
