### ISSUE TITLE
Could not find class 'rx.subscriptions.CompositeSubscription'

### ISSUE THREAD

**Issue by currymonkey** [ReactiveX/RxAndroid#422]
Could not find class 'rx.subscriptions.CompositeSubscription'
华为  emotion3.0 android版本4.4.2  型号PE-TL20

**Comment by JakeWharton** [comment]
This class comes from RxJava not RxAndroid and is a build misconfiguration. Please ask on StackOverflow with the 'rx-java' tag or post to the RxJava mailing list with more information about your build setup.
