### ISSUE TITLE
RxAndroid Crashing on 5G ---> io.reactivex.exceptions.OnErrorNotImplementedException: java.net.ConnectException: Failed to connect to {Some_IP}

### ISSUE THREAD

**Issue by shrutigoyal7032** [ReactiveX/RxAndroid#427]
Hi RXAndroid Dev
We are using Rx Android (2.0.1) dependency in our project and we figured out the after connecting my device to 5G, if I try to open my app, it is crashing. Here are the crash logs :- 

Terminating app due to an uncaught exception 'android.system.ErrnoException', reason: 'isConnected failed: EHOSTUNREACH (No route to host)'
Last Exception Backtrace
--
0 | io.reactivex.exceptions.OnErrorNotImplementedException: java.net.ConnectException: Failed to connect to /192.168.1.42:8484
1 | at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
2 | at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
3 | at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
4 | at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
5 | at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
6 | at android.os.Handler.handleCallback(Handler.java:739)
7 | at android.os.Handler.dispatchMessage(Handler.java:95)
8 | at android.os.Looper.loop(Looper.java:158)
9 | at android.app.ActivityThread.main(ActivityThread.java:7231)
10 | at java.lang.reflect.Method.invoke(Native Method)
11 | at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
12 | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
13 | Caused by: com.androidnetworking.error.ANError: java.net.ConnectException: Failed to connect to /192.168.1.42:8484
14 | at com.rx2androidnetworking.Rx2InternalNetworking$SimpleANObservable.subscribeActual(Rx2InternalNetworking.java:235)
15 | at io.reactivex.Observable.subscribe(Observable.java:10981)
16 | at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
17 | at io.reactivex.Single.subscribe(Single.java:2801)
18 | at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
19 | at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
20 | at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
21 | at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)

**Comment by JakeWharton** [comment]
This is not a problem with RxAndroid and not even with RxJava. You subscribed to a stream with a lambda and added no error handling code. For more info see https://github.com/ReactiveX/RxJava/wiki/Error-Handling.

**Comment by gurvinder9824** [comment]
@JakeWharton 
I have handled the throwable like below-

        getCompositeDisposable().add(getDataManager().callApi(request)
                .subscribeOn(getSchedulerProvider().io())
                .observeOn(getSchedulerProvider().ui())
                .subscribe((this::handleIcLoginApiSuccessResponse),
                        throwable -> getNavigator().onFailureIcLoginApi()));

Still getting the above issue, am I missing something?

**Comment by JakeWharton** [comment]
`OnErrorMissingConsumer` is defined here: https://github.com/ReactiveX/RxJava/blob/d506ddcc4c578f5372958dde86a7f17a9ee5cc59/src/main/java/io/reactivex/internal/functions/Functions.java#L701-L706. It's instantiated here: https://github.com/ReactiveX/RxJava/blob/d506ddcc4c578f5372958dde86a7f17a9ee5cc59/src/main/java/io/reactivex/internal/functions/Functions.java#L115. This reference is passed as the error handler here: https://github.com/ReactiveX/RxJava/blob/d506ddcc4c578f5372958dde86a7f17a9ee5cc59/src/main/java/io/reactivex/Single.java#L3270. This indicates that you are using the single-lambda overload of `subscribe` and not the two-lambda variant.

This isn't an RxAndroid problem. This is general RxJava usage. Your best bet would be seeking help on the RxJava mailing list or StackOverflow with the 'rx-java' tag.

**Comment by gurvinder9824** [comment]
Thanks @JakeWharton
