### ISSUE TITLE
How to use RxAndroid

### ISSUE THREAD

**Issue by dinesh-opg** [ReactiveX/RxAndroid#430]
I have integrated a third party library(opgsdk) it makes all the apis requests when i call their methods.Now i want to use the rxandroid for calling those methods.I am not clear how to make those method calls using the rxandroid.

**Comment by tristangrichard** [comment]
Use ```Observable.just(thirdPartyMethod())```

**Comment by JakeWharton** [comment]
For general usage help of RxJava I would recommend posting to StackOverflow with the 'rx-java' tag or asking on the mailing list which is linked in the README.

For getting started, there's a lot of resources on the RxJava wiki: https://github.com/ReactiveX/RxJava/wiki/Additional-Reading#introducing-reactive-programming

**Comment by artem-zinnatullin** [comment]
I have to say that `Observable.just(thirdPartyMethod())` is usually not what you want for wrapping method calls because it's not lazy, please take time to read docs linked by Jake.

**Comment by tristangrichard** [comment]
```Observable.create()``` is better but I would not recommend it for a Rx beginner

**Comment by dinesh-opg** [comment]
Thanks @JakeWharton  i will go through the documentation and if any issue i will raise in stackoverflow.
