### ISSUE TITLE
I can not catch error from ResourceSubscriber<Response<T>. for example url error 404

### ISSUE THREAD

**Issue by Widiyanto** [ReactiveX/RxAndroid#434]
`@Override`
    `public void requestLogin(LoginRequest loginRequest, Context context) {`
        `mView.loadingShowLogin();`
        `mDataManager.login(loginRequest)`
                `.compose(RxUtil.<Response<LoginResponse>>rxSchedulerHelper())`
               ` .subscribe(new ResourceSubscriber<Response<LoginResponse>>() {`

                    @Override
                    public void onNext(Response<LoginResponse> loginResponse) {
                        if (loginResponse.code() == Constants.success) {
                            mView.showLogin(loginResponse);
                            mView.loadingHideLogin();
                        }
                    }

                    @Override
                    public void onError(Throwable e) {
                        mView.loadingHideLogin();
                    }

                    @Override
                    public void onComplete() {

                    }
                });

    }

**Comment by JakeWharton** [comment]
This is a general RxJava usage question which is far better suited to be asked on StackOverflow with the 'rx-java' tag or on the RxJava mailing list. Links to both are available in the README. There's nothing specific to RxAndroid here.
