### ISSUE TITLE
RxJava 2.2.0 as the baseline dependency

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxAndroid#436]
Please consider releasing a new version of RxAndroid targeting RxJava 2.2.0 by default.

**Comment by JakeWharton** [comment]
Yes I was waiting for the release. Normally there's no point in doing this but since this will probably be the last RxAndroid release ever, I figured we'd wait.

**Comment by dimsuz** [comment]
Sorry for offtopic, but I'm curious why it is expected to be last? Some recent developments in either library (android SDK or RxJava) make this one obsolete or other reasons?

**Comment by JakeWharton** [comment]
It's stable.

**Comment by somnusM** [comment]
hello,i want to know how to use proguard in release version?

**Comment by JakeWharton** [comment]
Done!
