### ISSUE TITLE
RxAndroid 2.1.0 not available in Maven Central?

### ISSUE THREAD

**Issue by hameno** [ReactiveX/RxAndroid#439]
Not sure why but it seems RxAndroid 2.1.0 is not available in Maven Central:
https://search.maven.org/search?q=g:io.reactivex.rxjava2%20AND%20a:rxandroid&core=gav

There is no information where it is deployed (seem like it's only in jcenter?). The README should probably be updated or also push it to Maven Central.

**Comment by akarnokd** [comment]
Hi. I have restarted the sync process and the artifact should show up on maven shortly.

**Comment by hameno** [comment]
Great, it's available now! 👍
