### ISSUE TITLE
HandlerScheduler.scheduleDirect supports async option?

### ISSUE THREAD

**Issue by satoshun** [ReactiveX/RxAndroid#441]
RxAndroid support async option v2.1.0. now, it support only in `HandlerWorker.schedule`.

I think, `HandlerScheduler.scheduleDirect` should be support async option.
Because, some RxJava operator use `Scheduler.scheduleDirect` method (ex, Maybe.observeOn)

(i prepared source code in https://github.com/ReactiveX/RxAndroid/compare/2.x...satoshun:2.x)

**Comment by ZacSweers** [comment]
Hmm, that's a good shout. It'd be nicer if we could just use the hidden constructor of Handler to enable this at the handler level, but that implementation looks fine too. Looks like this affects all the observe/subscribe/dispose-"on" operators as well

@JakeWharton @adamp thoughts?

**Comment by JakeWharton** [comment]
I'd rather do the simple thing. I was hoping the recent release would be the last. Maybe this one will stick...

**Comment by adamp** [comment]
Consistency looks good to me.

**Comment by satoshun** [comment]
thx reply!

Handler level async can use from API28 via `Handler#createAsync`. It makes the code more complicated.

I think that it is unnatural not to consider async option in `HandlerScheduler.scheduleDirect`.

I opened PR, If there is no problem please review it.
