### ISSUE TITLE
RxAndroid to support -> Restrictions on non-SDK interfaces on Android Pie

### ISSUE THREAD

**Issue by KevinLeigh** [ReactiveX/RxAndroid#443]
As of Android Pie, there is restrictions for using non-SDK interfaces. Please see documentation here -> https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces

Will RxAndroid be updated to fully support Restrictions on non-SDK?

**Comment by JakeWharton** [comment]
No reflection nor hidden APIs are used.

**Comment by KevinLeigh** [comment]
@JakeWharton My apologies I re-looked at the Veridex dump and its actually for ReactiveX ->

```
#778: Reflection dark greylist Ljava/util/concurrent/CopyOnWriteArrayList;->remove potential use(s):      Lio/reactivex/internal/operators/observable/BlockingObservableIterable$BlockingObservableIterator;->remove()V
       Lokhttp3/internal/platform/JdkWithJettyBootPlatform;->buildIfSupported()Lokhttp3/internal/platform/Platform;
       Lio/reactivex/internal/operators/flowable/BlockingFlowableIterable$BlockingFlowableIterator;->remove()V
```

**Comment by JakeWharton** [comment]
That class also does no reflection and doesn't reference any Android APIs so you can ignore that false positive.

**Comment by KevinLeigh** [comment]
Thank you for the quick response, much appreciated :). I hear what you saying, Veridex gives a lot of false positives, next time I will look at the library source code before raising issue.
