### ISSUE TITLE
Driver Trait

### ISSUE THREAD

**Issue by gotev** [ReactiveX/RxAndroid#446]
Hi everybody,
by using RxJava2 + RxAndroid + RxKotlin on Android and RxSwift + RxCocoa on iOS, I've noted that on iOS there is a very useful trait for the UI called `Driver`, which is currently missing in RxAndroid.

I'm currently using this basic Kotlin implementation in my projects, which has only the essentials I need ported from: https://github.com/ReactiveX/RxSwift/tree/master/RxCocoa/Traits/Driver

```kotlin
interface SharingStratagy {
    val scheduler: Scheduler
    fun <Element> share(source: Flowable<Element>): Flowable<Element>
}

open class SharedSequence<SharingStrategy : SharingStratagy, Element>(source: Flowable<Element>,
                                                                      sharingStrategy: SharingStrategy) {
    internal val source = sharingStrategy.share(source)
    fun asFlowable() = source
}

object DriverSharingStrategy : SharingStratagy {
    override val scheduler: Scheduler
        get() = AndroidSchedulers.mainThread()

    override fun <Element> share(source: Flowable<Element>) = source.replay(1).refCount()
}

typealias Driver<Element> = SharedSequence<DriverSharingStrategy, Element>

fun <Element> Flowable<Element>.asDriver(onErrorJustReturn: Element): Driver<Element> {
    return Driver(
            observeOn(AndroidSchedulers.mainThread())
                    .onErrorReturn { onErrorJustReturn }, DriverSharingStrategy)
}

fun <Element> Flowable<Element>.asDriver(onErrorDriveWith: Driver<Element>): Driver<Element> {
    return Driver(
            observeOn(DriverSharingStrategy.scheduler)
                    .onErrorResumeNext(onErrorDriveWith.asFlowable()), DriverSharingStrategy)
}
```
Do you think it would be a valuable feature for RxAndroid? If so, I will port it to Java and make a PR, but I will need help on writing the tests.

**Comment by JakeWharton** [comment]
I don't really understand what it's for, why I would want to use it, or why it only supports Flowable. It also seems like it doesn't have anything to do with Android other than it's use of mainScheduler. It's entirely agnostic to the platform. Why not make this your own library that can be used with RxJava and any scheduler?

**Comment by gotev** [comment]
A `Driver` is basically a combination of main thread + shared subscriptions + no errors and it helps to easily bind reactive values to the UI. (Example: https://github.com/ReactiveX/RxSwift/issues/275#issuecomment-158416762) I use it to expose reactive properties from my View Models and then bind their values into the UI. It only supports Flowable in the snippet I posted, just because I didn't need to have other observables/traits support till now. In case of contribution here or with a library, the others will be supported, too.

I thought it would be useful to have this trait directly in RxAndroid without having to import other things, just to have a shorthand and easy way to bind values in the Android UI, but I opened the issue first to hear some opinions before making a move.

**Comment by JakeWharton** [comment]
This library is the bare minimum for using RxJava on Android.

I would recommend publishing this as your own library and seeing whether you can get meaningful adoption. We intentionally don't add anytjimg related to architecture because it's subjective to each consumer.

For example, in my apps there's a single view model instance which represents the entire state of the UI and so something like this wouldn't be needed.

**Comment by gotev** [comment]
Thank you @JakeWharton 👍 I discovered Rx thanks to you and I appreciate your feedback 😃

**Comment by chriskilpin** [comment]
@gotev Did you ever release this as it's own library? A small note Driver is part of RxCocoa which is the iOS UI component binding library (like RxAndroid) not part of the core RxSwift library.

**Comment by gotev** [comment]
@chriskilpin Jake made me think about that. 

> For example, in my apps there's a single view model instance which represents the entire state of the UI and so something like this wouldn't be needed.

He was right and I ended up doing exactly that using Android JetPack ViewModels. No need for a library, I can confirm!
