### ISSUE TITLE
Why android library

### ISSUE THREAD

**Issue by emartynov** [ReactiveX/RxAndroid#449]
I probably will ask dummy question - why should it be an android library? Because we need dependency on android.jar and it is problematic to get this dependency for kotlin/java libraries?

**Comment by JakeWharton** [comment]
That's pretty much it, yes.

**Comment by DaniloFurtado** [comment]
I always ask myself that. It's would be great.

**Comment by emartynov** [comment]
@JakeWharton, another dummy question, how about referencing android.jar from maven central?

**Comment by JakeWharton** [comment]
It's 7 years old and doesn't have the APIs we need

**Comment by artem-zinnatullin** [comment]
Wonder what's your motivation for RxAndroid to not be an android library?

If that's for JVM projects or unit tests, well it won't work without some implementation of classes referenced from Android SDK anyway

**Comment by emartynov** [comment]
We pull it to our lower level library. All modules on top have to be android libraries also. I assume it makes some build overhead.

**Comment by artem-zinnatullin** [comment]
If the only reason for your library to be an android library is RxAndroid, you can inverse the dependency on it and accept `Scheduler` as a runtime parameter rather than linking to RxAndroid at build time and then turn your library into a regular jvm lib.
