### ISSUE TITLE
Failed to resolve: io.reactivex:rxandroid:2.0.1

### ISSUE THREAD

**Issue by abdollahammail** [ReactiveX/RxAndroid#450]
Hi, i want to add RxJava and RxAndroid to my project but i get following error:

Error:(34, 20) Failed to resolve: io.reactivex:rxjava:2.1.5
Error:(35, 20) Failed to resolve: io.reactivex:rxandroid:2.0.1

i change the version of libraries but the problem didn't solved, i don't have any problem with another library but only with Rxjava and Rxandroid

my project level build.gradle:

buildscript {
    
    repositories {
        mavenCentral()
        maven{
            url 'https://jitpack.io'
        }
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven{
            url 'https://jitpack.io'
        }
        google()
        jcenter()
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}

my module level build.gradle:

apply plugin: 'com.android.application'
android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "baraayesh.fcmtest"
        minSdkVersion 17
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.google.android.exoplayer:exoplayer:2.9.6'
    implementation 'com.google.android.exoplayer:extension-rtmp:2.9.6'
    implementation 'com.liulishuo.filedownloader:library:1.7.6'
    implementation 'com.googlecode.mp4parser:isoparser:1.1.21'
    implementation 'com.afollestad.material-dialogs:core:2.0.3'
    implementation 'io.reactivex:rxjava:2.1.5'
    implementation 'io.reactivex:rxandroid:2.0.1'
}

**Comment by JakeWharton** [comment]
The groupId is `io.reactivex.rxjava2` not just `io.reactivex`

**Comment by gmarcus386** [comment]
io.reactivex.rxjava2

**Comment by 123abceng** [comment]
implementation 'io.reactivex.rxjava2:rxandroid:2.1.17' - can't resolve.
also 1.1.1, and all others...

**Comment by Simon-Richards** [comment]
Same problem here. JakeWharton's suggestion not helping.

**Comment by hen254** [comment]
Hello! And how do you change the groupId
