### ISSUE TITLE
[Discussion] Implement two-way binding

### ISSUE THREAD

**Issue by thuytrinh** [ReactiveX/RxAndroid#49]
This is not a new question though. While one-way binding can be done easily, how do you guys implement two-way binding?

For example, I have a Search model (searchModel) having a query text (searchModel.query). After two-way binding this query to an EditText, I expect that whenever searchModel.query changes, the EditText should reflect its new value. Also, whenever users type a new text on the EditText, searchModel.query should be set that new text.

Generally, given a modelA.propertyA and a modelB.propertyB. propertyA changes, propertyB changes accordingly. propertyB changes, propertyA changes accordingly. There must not be any endless update loops. propertyA and propertyB can be different types.

Thoughts?

**Comment by JakeWharton** [comment]
This is far out of scope for a fundamental core library for using RxJava on Android and would make for a good standalone library.
