### ISSUE TITLE
io.reactivex.exceptions.UndeliverableException at io.reactivex.plugins.RxJavaPlugins.onError(SourceFile:367)

### ISSUE THREAD

**Issue by PrashantpEdcast** [ReactiveX/RxAndroid#532]
I am getting this error on my crash report and I'm unable reproduce it. What is meaning of this error? and what are the way reproduce it and solve it.

**Comment by JakeWharton** [comment]
It means you lack an error callback somewhere that you've subscribed to a stream. This isn't a problem with RxAndroid, but a general usage question about RxJava. See https://github.com/ReactiveX/RxJava/wiki/Error-Handling, and feel free to ask future questions on StackOverflow with the 'rx-java' tag or on the RxJava mailing list (link in the project README).

**Comment by pavelsust** [comment]
@PrashantpEdcast  did you solved it? can you please share with me.
