### ISSUE TITLE
RXjava和RXAndroid到了2.0之后都不需要添加混淆了吗

### ISSUE THREAD

**Issue by MarkMingShuai** [ReactiveX/RxAndroid#537]

**Comment by MarkMingShuai** [comment]
为啥git上边没有看到混淆配置相关的

**Comment by JakeWharton** [comment]
I'm not sure what you're asking. Something about the 2.0 versions of both libraries...

**Comment by QiluXie** [comment]
Hey @JakeWharton , I'll try my best to translate:
I think @MarkMingShuai is asking if the obfuscation is still needed in version 2.0+ of RXjava and RXAndroid. The obfuscation configuration couldn't be found on git.

**Comment by JakeWharton** [comment]
Thanks @QiluXie!

RxJava 2 and RxAndroid 2 do not require rules for obfuscation. Only the 1.x versions needed special rules.
