### ISSUE TITLE
Convert Observable<List<ClassName>> to ArrayList

### ISSUE THREAD

**Issue by miPlodder** [ReactiveX/RxAndroid#539]
It's not an issue, but I'm not able to find a way to convert `Observable<List<ClassName>>` to ArrayList

**Comment by JakeWharton** [comment]
The map function. This isn't an RxAndroid question but one about RxJava in general. Please use the RxJava mailing list or StackOverflow with the 'rx-java' tag.

**Comment by gmarcus386** [comment]
Observable<List<ClassName>>
