### ISSUE TITLE
Hundreds of RxCachedThreadS

### ISSUE THREAD

**Issue by changxiangzhong** [ReactiveX/RxAndroid#550]
Hi thank you very much for this amazing project. Our product is using this framework and we have delivered into the market with great success. 

However we have observed considerable amount of Exception among our users. 
```
OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
```
On some of our test devices, we found that we get 200+ *RxCachedThreadS*. listed as following
```
android_device:/ $ ps -t 26731 |grep RxCachedThread| wc -l                                                                                                                                                  
201
```

My opinion is those cached thread is way too much. I found a relevant article [here](https://stackoverflow.com/questions/31294431/schedulers-io-creates-hundreds-of-rxcachedthreadschedulers). I've made sure every `Observable.create` calls the `onComplete` method. But the issue persists. 

Can you please provide some suggestions which orientation shall we look into? 

We are using RxJava:2.1.8 and RxAndroid:2.0.1

**Comment by JakeWharton** [comment]
RxAndroid does not create threads. Please file a bug on RxJava.
