### ISSUE TITLE
3.x: Where is the SNAPSHOT uploaded?

### ISSUE THREAD

**Issue by BraisGabin** [ReactiveX/RxAndroid#551]
I can't get the dependency: `io.reactivex.rxjava3:rxandroid:3.0.0-SNAPSHOT`. It seem that it's not uploaded to oss.sonatype: https://oss.sonatype.org/content/repositories/snapshots/io/reactivex/

Where is it?

**Comment by akarnokd** [comment]
It's on JFrog: https://oss.jfrog.org/libs-snapshot/io/reactivex/rxjava3/rxandroid/

**Comment by BraisGabin** [comment]
That worked! Probably a line in the README pointing this would help.

**Comment by JakeWharton** [comment]
PR welcome!

**Comment by ZacSweers** [comment]
This can be closed now (#553)
