### ISSUE TITLE
ERROR: Failed to resolve: io.reactivex.rxjava3:rxandroid:3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by yehuijifeng** [ReactiveX/RxAndroid#552]
implementation 'io.reactivex.rxjava3:rxandroid:3.0.0-SNAPSHOT'

ERROR: Failed to resolve: io.reactivex.rxjava3:rxandroid:3.0.0-SNAPSHOT

**Comment by JakeWharton** [comment]
Did you add the snapshot repository?

**Comment by j3g** [comment]
this isn't working for me.. I'll add it to the Readme after you help me ;)

```
buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url "https://oss.jfrog.org/libs-snapshot/io/reactivex/rxjava3/rxandroid/"
        }
    }
}
```

**Comment by akarnokd** [comment]
Do it one level up:

```groovy
buildscript {
    // ...
}

repositories {
    google()
    jcenter()
    maven {
        url "https://oss.jfrog.org/libs-snapshot"
    }
}
```

Edit: fixed the link.

**Comment by Godsel** [comment]
> 
> 
> Do it one level up:
> 
> ```groovy
> buildscript {
>     // ...
> }
> 
> repositories {
>     google()
>     jcenter()
>     maven {
>         url "https://oss.jfrog.org/libs-snapshot/io/reactivex/rxjava3/rxandroid/"
>     }
> }
> ```

Still not working for me !

**Comment by akarnokd** [comment]
Right, try removing the `/io/reactivex/rxjava3/rxandroid/` part.

**Comment by j3g** [comment]
Excellent, thank you for helping!! is this location good too? it seems to work.
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://oss.jfrog.org/libs-snapshot" }
    }
}
```
PS. put this in the project build.gradle (root build.gradle)

**Comment by Godsel** [comment]
> 
> 
> Right, try removing the `/io/reactivex/rxjava3/rxandroid/` part.

Thanks a lot, it works now
