### ISSUE TITLE
issue with the indirect dependency component reactive-stream License

### ISSUE THREAD

**Issue by dineshr93** [ReactiveX/RxAndroid#584]
Hi RxAndroid is dependent on Rxjava & Rxjava is dependent on reactive-stream which has CC-1.0 license that has the issue https://github.com/reactive-streams/reactive-streams-jvm/issues/536

That makes usage of RxAndroid problematic.

reactive-stream plans to release new version with MIT license.  which RxJava should be relied upon  https://github.com/ReactiveX/RxJava/issues/7418 Please consider upgrade to the new version of RxJava which uses reactive-stream which will **not** be under CC-1.0 license

please check this comment https://github.com/reactive-streams/reactive-streams-jvm/issues/536#issuecomment-1124497560 for dependency relationship

Thanks

**Comment by JakeWharton** [comment]
PRs welcome as the upstream issues appear to have been resolved.

**Comment by dineshr93** [comment]
@JakeWharton  Is this pull request okay?
