### ISSUE TITLE
Does RxAndroid have any plans to release a new version? 

### ISSUE THREAD

**Issue by mpkun** [ReactiveX/RxAndroid#589]
RxAndroid hasn't released a new version in two years,and i want to know it's release plans.If no new version is released, is there an EOS/EOL plan for the current version? Will someone keep maintaining it?
It would be a great help if I can get the answer.
Thank you!

**Comment by JakeWharton** [comment]
There are no plans to release a new version. There is also no end-of-life plan. The library is just stable.

If you think you have a bug, please file it with a small reproducing sample.
