### ISSUE TITLE
Add Sonatype secrets to repo for GitHub Actions usage

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxAndroid#591]
Alternatively, promote the ones in use for RxJava to organization secrets.

**Comment by akarnokd** [comment]
I'll do the secret part, but someone who understands this repo would need to update to the same signing method:

https://github.com/ReactiveX/RxJava/blob/3.x/build.gradle#L11
https://github.com/ReactiveX/RxJava/blob/3.x/build.gradle#L203-L207

**Comment by akarnokd** [comment]
The GHA code:
https://github.com/ReactiveX/RxJava/blob/3.x/.github/workflows/gradle_release.yml#L42-L57

**Comment by akarnokd** [comment]
Secrets done.

**Comment by JakeWharton** [comment]
Will do. That Gradle plugin is fairly ubiquitous in the Android world so we have a lot of experience with it.

**Comment by akarnokd** [comment]
To be safe, please do an RC1 release first.

**Comment by JakeWharton** [comment]
@akarnokd Do you have Sonatype access? Can you manually **drop** the 'ioreactivex-1418' repository?

**Comment by akarnokd** [comment]
On it.

**Comment by akarnokd** [comment]
Done.

**Comment by JakeWharton** [comment]
Thanks!
