### ISSUE TITLE
ERROR: Failed to resolve: io.reactivex.rxjava3:rxandroid:3.0.2

### ISSUE THREAD

**Issue by Beb3r** [ReactiveX/RxAndroid#599]
Hello there,

I encounter a small issue when adding dependencies to RxAndroid 3.0.2, gradle telling me that it cant resolve it.

When I put

`implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'`

No problem at all, but when I put:

`implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'` or the 3.0.1 version, i got the error.

I checked the maven repo and everything looks OK... have no idea why version 3.0.0 passes but not 3.0.1 or 3.0.2 ...

**Comment by hsy719007146** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JakeWharton** [comment]
Paste the full error message please.

**Comment by Beb3r** [comment]
```
> Error while evaluating property 'filteredArgumentsMap' of task ':common-java:compileKotlin'
   > Could not resolve all files for configuration ':common-java:compileClasspath'.
      > Could not resolve io.reactivex.rxjava3:rxandroid:3.0.2.
        Required by:
            project :common-java
         > No matching variant of io.reactivex.rxjava3:rxandroid:3.0.2 was found. The consumer was configured to find an API of a library compatible with Java 11, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'releaseApiPublication' capability io.reactivex.rxjava3:rxandroid:3.0.2 declares an API of a library, and its dependencies declared externally:
                 - Incompatible because this component declares a component, with the library elements 'aar' and the consumer needed a component, preferably in the form of class files
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about its target Java version (required compatibility with Java 11)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'releaseRuntimePublication' capability io.reactivex.rxjava3:rxandroid:3.0.2 declares a runtime of a library, and its dependencies declared externally:
                 - Incompatible because this component declares a component, with the library elements 'aar' and the consumer needed a component, preferably in the form of class files
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about its target Java version (required compatibility with Java 11)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')

```

Didnt see these messages before, guess it has something to do with Java 11 compatibility

**Comment by Beb3r** [comment]
my plugins:

plugins {
    id 'com.android.application' version '7.3.1' apply false
    id 'com.android.library' version '7.3.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.20' apply false
    id 'org.jetbrains.kotlin.jvm' version '1.7.20' apply false
    id 'com.google.dagger.hilt.android' version '2.43.2' apply false
    id "org.jetbrains.kotlin.kapt" version "1.7.10" apply false
    id 'androidx.navigation.safeargs' version '2.5.2' apply false
}

**Comment by JakeWharton** [comment]
RxAndroid is an aar and as a result can only be used in Android projects. That error message indicates that you are in a Java module with the Kotlin JVM plugin applied. You would need to be in a module with the Android library plugin or the Android application plugin applied for RxAndroid to work.
