### ISSUE TITLE
Why the HandlerScheduler class overrides scheduleDirect. It's not more explicit to let the HandlerWorker do the work

### ISSUE THREAD

**Issue by notcaremath** [ReactiveX/RxAndroid#610]

**Comment by hsy719007146** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by akarnokd** [comment]
A worker implementation is required to track all submitted tasks so they can be mass disposed. That adds overhead to use cases where only individual tasks need to be submitted. Such tasks are either tracked outside the scheduler or don't really need tracking.

**Comment by notcaremath** [comment]
I still don't understand why HandlerScheduler overrides the scheduleDirect method instead of using the Scheduler superclass method like IoScheduler and NewThreadScheduler

**Comment by akarnokd** [comment]
To avoid the uneccessary overhead of going through the HandlerWorker, as this particular type of scheduler can. Same logic as with `Schedulers.single()`.

**Comment by notcaremath** [comment]
thank you very much for your help
