### ISSUE TITLE
I would like to know when will you publish a new version?

### ISSUE THREAD

**Issue by littlemozart** [ReactiveX/RxAndroid#621]
Hi, it seems that this library has not been updated for quite some time. I wonder whether you have a update plan for it? I am your big fan and look forward to your updates. Thanks in advance!

**Comment by JakeWharton** [comment]
There have been no changes that require a release. The lack of releases indicates stability. This library is basically done. If all goes well, it will never see another release ever. If a bug fix or feature lands, despite being unlikely, we will make a release.
