### ISSUE TITLE
ContentResolver query Observable

### ISSUE THREAD

**Issue by dpsm** [ReactiveX/RxAndroid#71]
This is a proposal to implement an Observable that emits a Cursor while the Cursor has next and then closes the Cursor upon completion or failure.

This sounds like something useful that I can contribute with and I would like to hear thoughts before putting something together?

Something like: 

ContentObservables.query(PROJECTION, SELECTION, ...).subscribe(
    ...
    onNext(Cursor c) { // Calls once for each position in the cursor };
    ...
);

**Comment by JakeWharton** [comment]
This has been removed as part of #172 for a future release. Consider building on [SqlBrite's][1] ability to query a content resolver (not that I'm biased...).

[1]: https://github.com/square/sqlbrite

**Comment by djensen47** [comment]
I'm wondering if `BackpressureBufferLastOperator` from SqlBrite would make sense to include in RxAndroid. Nothing about it seems specific to SqlBrite. No?

**Comment by f2prateek** [comment]
Nothing about `BackpressureBufferLastOperator` is specific to Android either.

**Comment by djensen47** [comment]
> Nothing about BackpressureBufferLastOperator is specific to Android either.

Yeah, I was thinking that too. Add it to RxJava?
