### ISSUE TITLE
Add support for Android SDK dependencies

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxAndroid#83]
Taking off from [this discussion](https://github.com/ReactiveX/RxAndroid/pull/75#discussion_r20778360), it would be nice if this lib supported [Android's support annotations](http://tools.android.com/tech-docs/support-annotations).

At this point, though, we don't actually depend on any of the local repositories that the SDK uses; it's just using the few Android libs floating around in jcenter (which are rather out of date). This keeps the library simpler but limits our ability to add more recent support libraries.

Thoughts? Should we just embrace the local m2 repo?

**Comment by JakeWharton** [comment]
Resolved by #189.
