### ISSUE TITLE
"bindFragment" Method Signature

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxAndroid#95]
It takes `Object` and uses ugly `instanceof` and runtime API checks. Why not just have two overloads?

**Comment by JakeWharton** [comment]
Ok, the way it stands now this will actually fail at compilation time, not runtime (see #136).

This is because the methods become "pure" overloads of each other. That is, they have the same name, return type, number of parameters, and type of second parameter. They only differ by the type of the first parameter.

In the very few times I've done this, the overloads have differed in some way even if that difference produces the same API at the call site. A prime example: varargs.

Changing the support-v4 variant's method signature to the following:
```java
bindFragment(android.support.v4.app.Fragment fragment, Observable<T> source, Object... dummy)
```
actually works! You can also rename the method to `bindSupportFragment` and it will work. Neither approach fails at runtime.

So, which do we like?

**Comment by rosshambrick** [comment]
A little late for a reply I guess, but I'd prefer `bindFragment(...)` for two reasons.  1- It wouldn't be a breaking change and 2 - the addition of 'Support' doesn't add much value.  This is assuming it technically works just as well either way.

**Comment by JakeWharton** [comment]
Per my comment above, it does not work.

**Comment by rosshambrick** [comment]
Ah yes, I missed `Object... dummy` the first time somehow. Carry on
